### PR TITLE
chore: deleted outdated files which are no longer used.(fixes issue#1482)

### LINKED ISSUE #1482: [Bug]: Outdated files
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There was some outdated files for login page
They can be safely removed and improve the storage .

### Expected behavior

By deleting the useless files we can free up space

### Add ScreenShots

Screenshot 2024-10-09 234948

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Nivesh2003**
# chore: deleted outdated files which are no longer used.(fixes issue #1482 )

Title : chore: Deleted outdated files from the codebase (fixes issue #1482)

Issue No. : 1482

Code Stack : html 

Close #1482 

# Description

I deleted some outdated files as i mentioned in the issue.

# Video/Screenshots (mandatory)

Screenshot 2024-10-20 140004

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [x] Other (specify): _______Code base update ________

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing
- [x] I have Starred the Repository.

# Additional context:

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24 Extended`
- [x] I am contributing under `Hacktoberfest'24`

### CODE REVIEW

**Comment by Nivesh2003** [comment]
why title needs formatting ? What does that means

**Comment by rishika105** [comment]
chore: deleted outdated files which are no longer used.(fixes issue #1537) 
Try this as title.

**Comment by Nivesh2003** [comment]
@rishika105 hello i put that title

**Comment by rishika105** [comment]
you need to put that title at above the main title that is highlighed above PR title. Look there will be option to edit change it there and add that full title just copy the below line full and try it.
chore: deleted outdated files which are no longer used.(fixes issue #1537)

**Comment by Nivesh2003** [comment]
ok did that but still failing

**Comment by rishika105** [comment]
No you havent done it. Change the main title . And write the correct issue number.

**Comment by Nivesh2003** [comment]
I did as same as you please tell me the part which is wrong here
Screenshot 2024-10-20 215319

**Comment by rishika105** [comment]
image
Change this title to

**Comment by rishika105** [comment]
image
Look like this. There is the edit button change it.

**Comment by Nivesh2003** [comment]
I was doing something else till yet omg , thank you for clearing it , I really appreciate your help @rishika105

**Comment by rishika105** [comment]
> I was doing something else till yet omg , thank you for clearing it , I really appreciate your help @rishika105

Welcome:)

**Review by apu52 — APPROVED** [review]
@Nivesh2003 thanks for the contribution

**Pull request merged**
