### PR TITLE
Made the Website Responsive in Desktop Version

### LINKED ISSUE #178: BUG : Make the Website responsive in Desktop version
**Describe the bug**

Hello All,
The webpage is not really responsive for all the Zoom portion in the webpage desktop version & also the color is not static in the background

**Expected behavior**

- I want to make the background in one static color or some animation design 
- & also make the website desktop responsive to all the zoom options
- & also make the background with some animation & maybe with some bgm music

**Screenshots (Mandatory)**

image
make the alignments ok

image
Make the background well like this . it's a demo.

**Additional Context (Mandatory )**

### Those whoever want to work on this issue comments first with JWOC mentioned on it I will assign it to HER/HIM

***Are you contributing under any open-source program ?***

JWOC'24

### PR DESCRIPTION
**Pull request by SohanRC**
# Title and Issue number 

Title : Made the Website Responsive in Desktop Version

Issue No. : #178 

Code Stack :  HTML , CSS , JS

Close #178 

# Video/Screenshots (mandatory)

https://github.com/apu52/Travel_Website/assets/124901633/000b274c-e5bd-44c8-a4fa-de45a8969475

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

Yes , in JWOC 2024.

### CODE REVIEW

**Comment by SohanRC** [comment]
@apu52 I have resolved the Conflicts. Please review it now

**Review by apu52 — CHANGES_REQUESTED** [review]
@SohanRC This maybe a great contribution. But I can't really want this type of bg changes in my website . So , sorry this PR can't me merged.

**Comment by apu52** [comment]
@SohanRC But I am giving you 2 more days to make better contributions on this issue. Hope to see your valuable contribution.

**Comment by SohanRC** [comment]
> @SohanRC This maybe a great contribution. But I can't really want this type of bg changes in my website . So , sorry this PR can't me merged.

But you said that you wanted that animation

**Comment by SohanRC** [comment]
@apu52 You said to resolve the merge contributions so that you can merge it
I am still fixing the About us section

**Comment by apu52** [comment]
> @apu52 You said to resolve the merge contributions so that you can merge it I am still fixing the About us section

ok look @SohanRC I have mentioned that is was a demo. you can make more farther good UI changes in the repo on your preference. the last UI change was not up to the mark so that I have closed the PR

**Pull request closed without merging**
