### PR TITLE
feat: FAQ Page inproved

### LINKED ISSUE #909: [Feature Request]: Improve the FAQ page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The faq now is not well alligned and has irregular size issue

### Use Case

Very important part of a travel website

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by sau-mili**
# Title and Issue number 

Title :

Issue No. : #909 

Code Stack : HTML, CSS, JS

Close #909

# Description

- Added new accordion system to the page
- Added navabar
- Edited minute bugs in index.html file
- Also CSS for the FAQ page is done

# Video/Screenshots (mandatory)

# NOW
https://github.com/apu52/Travel_Website/assets/146661411/d7752167-e4d3-49bd-8d06-9153859d8d9c

Screenshot 2024-06-28 010907
# BEFORE
Screenshot 2024-06-28 010414

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by itsekta** [comment]
Hey @sau-mili, have you checked the UI on the preview link above. The UI for FAQ now looks like this

image


This can be improved with a nice UI

**Comment by sau-mili** [comment]
The one that you shared is on the home page, and I edited the specific “Faqs” page.
Do you want me to edit the home page as well?

**Comment by itsekta** [comment]
> The one that you shared is on the home page, and I edited the specific “Faqs” page. Do you want me to edit the home page as well?

Okay got it, just checked the faq page nice work 👍

**Comment by itsekta** [comment]
Improved FAQ page PR #926

**Comment by sau-mili** [comment]
What’s wrong then? What do i need to improve?

**Comment by itsekta** [comment]
Nothing is wrong, I have just closed the issues as you have already created a pull request that is #926

**Comment by sau-mili** [comment]
But it was not merged. That’s why asking

**Review by apu52 — CHANGES_REQUESTED** [review]
@sau-mili although I can see your brilliant changes in the Footer FAQ page , but along side in your pR the home page FAQ is not aligned correctly (maybe the CSS file of that is not linked with the HTML file) That has already been Identified by the Mentor @itsekta .thanks @itsekta 

@sau-mili please solve the problems in your PR mentioned above so that I can approve your PR

**Comment by sau-mili** [comment]
Do you mean to align the faq page and home page faq section with similar UI?

**Comment by itsekta** [comment]
Hey @sau-mili, the /faq pages looks perfect but the landing page faq section still need some improvement
Firstly it isn't collapsible like it was earlier and secondly why are we showing both the icons at same time (the arrow down and close icon), should it be something like if it is open show close icons and if it isn't open down arrow icon and vice versa.

image

**Comment by sau-mili** [comment]
okay i will fix it

**Comment by sau-mili** [comment]
please check now
image

**Review by apu52 — APPROVED** [review]
@sau-mili very good work

**Pull request merged**
