### PR TITLE
feat: Counter added, Numeric status section improved

### LINKED ISSUE #911: [Feature Request]: Add counter, improve numerical sections
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add numerical counter when scrolled, to no of tourists and desticstions section right after about

### Use Case

For better responsiveness, UI as well as UX

### Benefits

_No response_

### Add ScreenShots

Screenshot 2024-06-27 022059

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by sau-mili**
# Title and Issue number 

Title :

Issue No. : #911 

Code Stack : 

Close #911

# Description

# Video/Screenshots (mandatory)

## BEFORE: 
Screenshot 2024-06-29 025743
## AFTER:

https://github.com/apu52/Travel_Website/assets/146661411/a165d2a8-6ec2-4266-b6eb-57d661a18a5c

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@sau-mili this PR has merging conflicts .Please try to resolve the conflicts so that I can review /merge the PR . Or best thing u can submit a total new PR (making a new branch in your PR) to avoid the conflicts

**Comment by sau-mili** [comment]
please check now

**Comment by apu52** [comment]
> please check now

still have merging conflicts

**Comment by sau-mili** [comment]
can you check now?

**Review by apu52 — APPROVED** [review]
@sau-mili it's really well made changes

**Pull request merged**
