### PR TITLE
feat: Fixing Login Option

### LINKED ISSUE #1087: Fixing Login option
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The login/sign up and view Section seems odd in terms of their color and font. I would like to fix it to make it visually appealing.

### Use Case

Improvement of UI

### Benefits

_No response_

### Add ScreenShots

Screenshot 2024-07-15 235440

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by AshmitaBarthwal**
# Title and Issue number 

Title : Fixing Login Option

Issue No. : #1087

Code Stack : CSS

Close #1087

# Description
Added background according to light and dark mode as per website's color code to the buttons.

# Video/Screenshots (mandatory)
BEFORE IN LIGHT MODE:
Screenshot 2024-07-20 162215

BEFORE IN DARK MODE:
Screenshot 2024-07-20 162200

AFTER IN LIGHT MODE:
Screenshot 2024-07-20 160027

AFTER IN DARK MODE:
Screenshot 2024-07-20 160040

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [X] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by AshmitaBarthwal** [comment]
@apu52 Please review my PR.

**Comment by AshmitaBarthwal** [comment]
@apu52 Review this PR once.

**Comment by AshmitaBarthwal** [comment]
@itsekta please review this PR once.

**Review by apu52 — APPROVED** [review]
@AshmitaBarthwal it's good

**Review by apu52 — CHANGES_REQUESTED** [review]
@AshmitaBarthwal but why this unnecessary commits present in this PR , as it does not have any linking with this...Please try to delete all of the unnecessary  commit otherwise I can't merge this PR.
& I would like to suggest u to make different branches for different pr

**Comment by AshmitaBarthwal** [comment]
Okay I will delete extra things

**Comment by AshmitaBarthwal** [comment]
@apu52 Please check the above changes.

**Comment by AshmitaBarthwal** [comment]
@apu52 i have deleted the unnecessary.

**Comment by AshmitaBarthwal** [comment]
@apu52 Please review the PR.

**Pull request closed without merging**
