### PR TITLE
feat: added dark theme for all trip package pages

### LINKED ISSUE #1262: [Feature Request]: Add dark mode for all 3 best trip packages pages
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently our website's best trip packages' individual pages don't have a theme toggle button and the dark theme, I would like to implement both the things

### Use Case

Users can specifically choose between 2 different themes according to their convenience

### Benefits

_No response_

### Add ScreenShots

p3
p4

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Asymtode712**
# Title and Issue number 

Title : Added dark theme for all 12 best trip package pages

Issue No. : #1262 

Code Stack : HTML ,CSS, Javascript

Close #1262 

# Description

- Added dark theme for all the 12 destination pages of best trip package
- Modified shadow effects for better visibility in dark mode.
- Adjusted button and interactive element styles for dark mode compatibility.
- Ensured contrast and readability in dark mode for all text elements.

# Video/Screenshots (mandatory)

https://github.com/user-attachments/assets/80f17aa6-0b82-4400-ac82-5631866dd829

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

##Are you contributing under any Open-source programme?

- [X] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by Asymtode712** [comment]
@apu52 please review and merge this PR

**Review by apu52 — CHANGES_REQUESTED** [review]
@Asymtode712 the dark theme u have made is not matching with the dark theme UI of the website ,please make it in the same manner .

**Comment by Asymtode712** [comment]
@apu52 done the changes, please check and merge the PR

**Review by apu52 — APPROVED** [review]
@Asymtode712 very good work

**Pull request merged**
