### PR TITLE
Documentation

### LINKED ISSUE #61: Documentation
**Is your Documentation related to a problem? Please describe.**
No, my documentation is not solely related to a problem. It moreover an enhancement of the current project.

**Describe the solution you'd like**
Yes, I want to add a toggle switch, where on clicking on it, the entire website would change from light to dark theme and vice versa. The would also include change of font and button colors.

**Prototype Screenshot/Demo Video(Mandatory )**
Before clicking the toggle key :
Screenshot 2024-01-15 231716

After clicking the toggle key :
Screenshot 2024-01-15 233015

Its just a dummy, this change would be applied to entire website.

***Are you contributing under any open-source program ?***
No, this is my first.

### PR DESCRIPTION
**Pull request by 13AdityaDey**
# Title and Issue number 

Title : Documentation

Issue No. :#61

Code Stack : 

Close #61 

# Video/Screenshots (mandatory)

https://github.com/apu52/Travel_Website/assets/140962818/0f16d741-e746-4faa-bede-f0f666ec942b

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**
A toggle button is add to switch between light to dark theme.

***Are you contributing under any Open-source programme?***

### CODE REVIEW

**Review by apu52 — APPROVED** [review]
OK

**Comment by apu52** [comment]
@13AdityaDey Thank you for submitting your PR & valuable contribution. 
Can you please mention your full name here so that I can update the leaderboard

**Comment by 13AdityaDey** [comment]
> @13AdityaDey Thank you for submitting your PR & valuable contribution. Can you please mention your full name here so that I can update the leaderboard

Thank you for helping me out for submitting my first PR!! 
Name :- Aditya Dey

**Comment by 13AdityaDey** [comment]
> @13AdityaDey Thank you for submitting your PR & valuable contribution. Can you please mention your full name here so that I can update the leaderboard

Btw where can I see the leaderboard? 😅

**Comment by apu52** [comment]
> > @13AdityaDey Thank you for submitting your PR & valuable contribution. Can you please mention your full name here so that I can update the leaderboard
> 
> Btw where can I see the leaderboard? 😅

In the official JWOC website.
You can get all the details in Discord JWOC channel

**Pull request merged**
