### PR TITLE
feat: Updated Footer section bug

### LINKED ISSUE #837: BUG: Footer section improvement
**Describe the bug**
In the footer section, google image height is small and select language dropdown can be enhanced.

**Expected behavior**
Google image height can be increased and dropdown can be given few properties to look attractive.

**Screenshots (Mandatory)**
Screenshot 2024-06-09 150107

**Additional Context (Mandatory )**
The google image in footer section should have a considerable height.

***Are you contributing under any open-source program ?***
gssoc 2024

### PR DESCRIPTION
**Pull request by Siddhipogakwar123**
# Title and Issue number 

Title :Updated Footer section bug

Issue No. :837

Code Stack : 
Lnguages:
HTML
CSS
JavaScript

Close #837

# Description

Updated and improved the footer component and increased the orientation of Google translates Network Image and also improved the "Select Language" dropdown.

# Video/Screenshots (mandatory)

image

# Type of PR

- [X] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

# Additional context:

I have changed the size of google image and improved the footer section and also improved "Select Language" dropdown

##Are you contributing under any Open-source programme?

- [X] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@Siddhipogakwar123 this PR has merging conflicts .Please try to resolve the conflicts so that I can review /merge the PR . Or best thing u can submit a total new PR (making a new branch in your PR) to avoid the conflicts

**Comment by Siddhipogakwar123** [comment]
Okay sir

**Comment by Siddhipogakwar123** [comment]
Done sir!

**Comment by apu52** [comment]
> Done sir!

Don't call me Sir first of all .I  am Just a student
& secondly there is some recent changes in the footer section , so want to request you to please submit a new pR making a new branch that will help u to avoid the conflicts.

**Pull request closed without merging**
