### PR TITLE
Adding Image gallery

### LINKED ISSUE #34: FEATURE_REQUEST : Adding Animation to Our Trip Section
**Is your feature request related to a problem? Please describe.**
No it's actually not a problem, its aim is to give better user experience.

**Describe the solution you'd like**
I would like to add rotating image gallery to your 'Our Trip Gallery' Section. So that makes this website more attractive.

**Describe alternatives you've considered**
If you doesn't like to include rotating gallery feature, I can add any other framework components

**Demo Video/Screenshot (Mandatory )**
Screenshot 2024-01-15 014932

***Are you contributing under any open-source program ?***

under JWOC 2024.

### PR DESCRIPTION
**Pull request by Prithwi32**
# FEATURE_REQUEST : Adding Animation to Our Trip Section #34

Title : FEATURE_REQUEST : Adding Animation to Our Trip Section.

Issue No. : #34 

Code Stack : HTML, CSS, Js

Close #34 

# Video/Screenshots (mandatory)
https://github.com/apu52/Travel_Website/assets/115262737/067071f8-387b-4dac-ba14-105241de2b18

# Checklist:
- [X ] I have mentioned the issue number in my Pull Request.
- [ X] I have commented my code, particularly in hard-to-understand areas
- [X ] I have gone through the  `contributing.md` file before contributing

***Are you contributing under any Open-source programme?***
Yes,under JWOC

### CODE REVIEW

**Comment by Prithwi32** [comment]
@apu52  Please could you review this and let me know the feedback. Thank You!

**Review by apu52 — APPROVED** [review]
OK

**Comment by apu52** [comment]
@Prithwi32 Thank you for your valuable contribution. 
The feature you have added are really great

**Comment by Prithwi32** [comment]
> @Prithwi32 Thank you for your valuable contribution. The feature you have added are really great

You made my day :)

**Pull request merged**
