### PR TITLE
I am trying to improve the testimonial section and faqs section also …

### LINKED ISSUE #529: Improve the testimonial Section
I think if the Testimonial section had a different background color so it would have better UI and also it is not aligned properly.I would also like to make it responsive.
Please Assign me this issue with the label of GSSOC.

Screenshot:- 

image

### PR DESCRIPTION
**Pull request by suhanachaudhary**
…do the some changes

# Title and Issue number 

Title :changes in testimonial and faqs section also do some changes

Issue No. :#529

Code Stack : html,css

Close #529 

# Video/Screenshots (mandatory)

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

### CODE REVIEW

**Comment by suhanachaudhary** [comment]
please review my updation

**Comment by Ghanshyam89** [comment]
@apu52 This issue has not been assigned to him before that only he raised this PR. Kindly look into it.

**Comment by apu52** [comment]
> @apu52 This issue has not been assigned to him before that only he raised this PR. Kindly look into it.

Thanks sir for reminding me

**Review by apu52 — COMMENTED** [review]
@suhanachaudhary please don't submit any type of PR until 7 unless you get assigned to any issue .now you are assigned. you can submit your PR , But I am closing this old PR .you can now submit your new PR.

**Pull request closed without merging**
