### PR TITLE
feat: Added Background for text visibility

### PR DESCRIPTION
**Pull request by Archi-shaw**
Fixes issue#1661

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@Archi-shaw try to follow the PR template which is already given in the repo , so That i will get all the details of your pr from it .Please try to fill up the pr form so that i will merge your pr

**Comment by Archi-shaw** [comment]
@apu52  Where can I find that template? I am not able to find it out.

**Comment by apu52** [comment]
@Archi-shaw the template will be automatically there whenever u will submit a new PR , I think maybe u have deleted it mistakenly , u can check over other pr's in this repo details

**Comment by apu52** [comment]
@Archi-shaw will you submit a new PR , so that i can close this PR or will edit in this pr

**Comment by Archi-shaw** [comment]
@apu52 Closing this pr and creating new one.

**Pull request closed without merging**
