### PR TITLE
Added Navbar to Feedback Page

### LINKED ISSUE #469: Feature_Request:  Added missing Navbar on the feedback page
**Is your feature request related to a problem? Please describe.**

the Navbar was missing in the feedback section  and unable to navigate back so , itis important to add Navbar to feedback page also

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
before screenshot
Screenshot (1692)

after updating

Screenshot (1693)

***Are you contributing under any open-source program ?***
yes girlscript summer of code (Gssoc'24)

### PR DESCRIPTION
**Pull request by SadafKausar2025**
# Title and Issue number 

Title :Added missing Navbar on the feedback page 

Issue No. :#469

Code Stack : 

Close #469

the Navbar was missing in the feedback section  and unable to navigate back so , itis important to add Navbar to feedback page also

**Describe the solution you'd like**

**Describe alternatives you've considered**

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***
Gssoc24(girscript summer of code)

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
original page : without Navbar on Rating page

Screenshot (1692)

After updating

Screenshot (1693)

**Comment by SadafKausar2025** [comment]
Hey @apu52 
Can you please review it and merge this PR?

**Review by apu52 — CHANGES_REQUESTED** [review]
@SadafKausar2025 the navbar is added but it's not working .please make it working.

**Comment by SadafKausar2025** [comment]
Hey @apu52 
Now the Navbar is working properly.
Please merge this PR.

**Comment by apu52** [comment]
@SadafKausar2025  There are still merge conflicts present in the PR. I would like to suggest you to make a complete new PR on this issue making a new branch on your forked repo So that it will be helpful.
I am closing this PR but you still have more 5 days to complete your issue & submit your PR

**Pull request closed without merging**
