### PR TITLE
after click on book now on start.html page checkout need to be aligned 

### LINKED ISSUE #508: Feature_Request after click on book now on start.html page checkout need to be aligned
**Is your feature request related to a problem? Please describe.**
Request after click on book now on start html page checkout need to be aligned 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
Screenshot_20240519_095514

***Are you contributing under any open-source program ?***
Gsoc 24

### PR DESCRIPTION
**Pull request by kapilG0**
# Title and Issue number 
Title : after click on book now on start.html page checkout need to be aligned 

Issue No. : #508 

Code Stack : 

Close #508

# Video/Screenshots (mandatory)

https://github.com/apu52/Travel_Website/assets/59639410/61c1bff5-f23f-4209-845b-1831db7a8850

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***
Gssoc 24

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@kapilG0 I have gone through your changes . but I really can't under stand what do you exactly want to change as you have done only the changes in the bali.css file . 
Can you please explain????

**Comment by kapilG0** [comment]
> @kapilG0 I have gone through your changes . but I really can't under stand what do you exactly want to change as you have done only the changes in the bali.css file . Can you please explain????

Hello @apu52 i request please check above attached video and checked checkout previous was different now it is different

**Comment by apu52** [comment]
> > @kapilG0 I have gone through your changes . but I really can't under stand what do you exactly want to change as you have done only the changes in the bali.css file . Can you please explain????
> 
> Hello @apu52 i request please check above attached video and checked checkout previous was different now it is different

Okay .I understand.

**Comment by kapilG0** [comment]
> > > @kapilG0 I have gone through your changes . but I really can't under stand what do you exactly want to change as you have done only the changes in the bali.css file . Can you please explain????
> > 
> > 
> > Hello @apu52 i request please check above attached video and checked checkout previous was different now it is different
> 
> Okay .I understand.

Ok thank you 👍

**Review by apu52 — APPROVED** [review]
@kapilG0 good work

**Pull request merged**
