### PR TITLE
feat: UI of rate us page improved with better alignment and css styles

### LINKED ISSUE #711: Feature_Request: Enhance UI of Rate us section
**Is your feature request related to a problem? Please describe.**
I would like to make the UI such that it matches the overall theme of the website

**Describe the solution you'd like**
make better CSS styles, match color themes, improve flex designs and make it responsive

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
Will add once assigned

***Are you contributing under any open-source program ?***

GSSOC'24

### PR DESCRIPTION
**Pull request by sau-mili**
# Title and Issue number 

Title : Improved UI of Rate us page

Issue No. : #711

Code Stack :  HTML CSS

Close #711

# Description

- I have improved the overall UI of the page
- I have changed the background to match the theme
- I have made column wise CSS for the whole section
- I have added a image to show that the page takes feedback from user
- I made the stars and rating in one row with equal space between to make it look more professional
- I have also added HRs to define end of each questions
- I have also fixed hover effects of buttons and made their appearance better to match the parent home page

# Video/Screenshots (mandatory)

before:
Screenshot 2024-06-08 014452

AFTER:
Screenshot 2024-06-08 014846

VIDEO:

https://github.com/apu52/Travel_Website/assets/146661411/ee3a7fab-9c4a-4c33-b630-d3bd3c9dff61

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

### CODE REVIEW

**Comment by sau-mili** [comment]
@apu52 can you please check this?

**Review by apu52 — CHANGES_REQUESTED** [review]
@sau-mili there is some recent changes in the rate us page so that your PR is facing some merging conflicts . so I would like to request you to submit a new PR making a new branch in your forked PR to avoid all of the conflicts 
Otherwise the features u have added are working well .I have checked it

**Comment by sau-mili** [comment]
Okay, I will change that, please wait for it before adding new similar things

**Comment by sau-mili** [comment]
Can you check now?

**Review by apu52 — APPROVED** [review]
@sau-mili Now every feature is working really well

**Comment by sau-mili** [comment]
Thanks, please check my other Issue. Also, can I raise more than one issue? I have college tomorrow, so I could just raise two issues, if assigned, I could work on those during free time in college itself.

**Pull request merged**
