### PR TITLE
feat: Added new TN blog

### PR DESCRIPTION
**Pull request by keerthika-18**
# Title and Issue number 

Title :feat: Added new TN blog

Issue No. :#1168

Code Stack : #1168

Close #1168

# Description

i included the additional  blog feature to it

# Video/Screenshots (mandatory)

Screenshot 2024-07-21 210850
Screenshot 2024-07-21 210903

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by keerthika-18** [comment]
actually it is an amazing web to practice

**Comment by apu52** [comment]
@keerthika-18 thanks for raising the pR . Can you please provide me what is your assigned issue no.???

**Comment by keerthika-18** [comment]
hii!! TQ for ur reply :pleading_face:!!!!!!
As  i am newbie to this environment ..I am not sure about the issue no but i think it might be  #1168  ..

**Comment by apu52** [comment]
> hii!! TQ for ur reply 🥺!!!!!! As i am newbie to this environment ..I am not sure about the issue no but i think it might be #1168 ..

ok I understand , But that's the PR no. , not issue no. & I also think that u have not created any type of issue before making this PR . SORRY to say But I have to close this PR , as this PR is unplanned

**Comment by apu52** [comment]
but don't worry @keerthika-18 **as u are a newbie, I want to suggest you to please go through the CONTRIBUTING.md file to check all the rules for contributions , so that u will get an idea that how to contribute in this repo .**
& after that if u face any doubt u can simply reach out to me or mentors in discord .
HAPPY CODING!!!!!!!!!!!

**Comment by keerthika-18** [comment]
ohhh,, it's okay...i seen the kashmir blog in the code so i did the TN blog..okay its fine ..BTW TQ:smiley:

**Pull request closed without merging**
