### PR TITLE
feat: Trip Gallery Page is Been Updated

### LINKED ISSUE #925: [Feature Request]: Trip Gallery Changes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Benefits

_No response_

### Add ScreenShots

Screenshot 2024-06-27 230043

@apu52 please assign this to me under GSSOC24

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by AbheetHacker4278**
# Title and Issue number 

Title :
### [Feature Request]: Trip Gallery Changes

Issue No. :
#925

Code Stack : 

Close #925

# Description

Here in this PR i have do some of the major changes in Trip Gallery , i have improved the User Interface of the Page , by using cool animation , so due to this the experience of the users also get enhanced.

# Video/Screenshots (mandatory)

BEFORE
Screenshot 2024-06-27 230043

AFTER
image

### Video

https://github.com/apu52/Travel_Website/assets/114290748/e4dbeb5c-48c8-48f0-a25f-a12810c9a943

# Type of PR

- [X] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

# Additional context:
@apu52 please review this PR and merge with main branch under Gssoc24

##Are you contributing under any Open-source programme?

#GSSOC24

- [X] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by itsekta** [comment]
Hey @AbheetHacker4278, can you add an overlay layer on these card images so that the content on the images will be move visible on hovering on it

**Comment by AbheetHacker4278** [comment]
> Hey @AbheetHacker4278, can you add an overlay layer on these card images so that the content on the images will be move visible on hovering on it

Okay i will do it

**Comment by AbheetHacker4278** [comment]
@itsekta I have done the necessary changes  , please review it and merge it with main branch

**Comment by AbheetHacker4278** [comment]
@itsekta please also add Gssoc labels with level 2

**Comment by AbheetHacker4278** [comment]
@itsekta if you like the changes please merge with main branch

**Comment by AbheetHacker4278** [comment]
@itsekta @apu52 please merge into main branch if there is no errors

**Comment by itsekta** [comment]
Hey, @AbheetHacker4278 can you also make it responsive for mobile screen as well

**Comment by AbheetHacker4278** [comment]
> Hey, @AbheetHacker4278 can you also make it responsive for mobile screen as well



> Hey, @AbheetHacker4278 can you also make it responsive for mobile screen as well

Okay i will do that in new PR , Because this take some time and i also have to re structure the code base from start to end , so better you merge this pr with main branch and tommorow i will open an new issue you just approve it, is it fine.

**Comment by AbheetHacker4278** [comment]
> Hey, @AbheetHacker4278 can you also make it responsive for mobile screen as well

Because code base are in very bad structure very messy , thats why i am asking you

**Comment by AbheetHacker4278** [comment]
> Hey, @AbheetHacker4278 can you also make it responsive for mobile screen as well

Please merge it , tommorow i will open new issue and accept it also 🙏

**Review by apu52 — APPROVED** [review]
@AbheetHacker4278 the changes u have made are really cool

**Review by apu52 — CHANGES_REQUESTED** [review]
image

but here I can see there is a bug in your Deployed pR , please try to resolve this So that I can merge your PR

**Comment by AbheetHacker4278** [comment]
> image
> 
> but here I can see there is a bug in your Deployed pR , please try to resolve this So that I can merge your PR

I havent see any kind of bugs from my side , please check it again please. and i think ,  this is not my PR sir.

image

**Comment by AbheetHacker4278** [comment]
> image
> 
> but here I can see there is a bug in your Deployed pR , please try to resolve this So that I can merge your PR

**Comment by apu52** [comment]
> > image
> > but here I can see there is a bug in your Deployed pR , please try to resolve this So that I can merge your PR
> 
> I havent see any kind of bugs from my side , please check it again please. and i think , this is not my PR sir.
> 
> image

not this changes what u have made .the above image slider is facing some bugs

**Comment by AbheetHacker4278** [comment]
@apu52 all bugs is been removed , please review it and merge it with main branch

**Review by apu52 — APPROVED** [review]
@AbheetHacker4278 all the changes are really good

**Comment by apu52** [comment]
> > Hey, @AbheetHacker4278 can you also make it responsive for mobile screen as well
> 
> > Hey, @AbheetHacker4278 can you also make it responsive for mobile screen as well
> 
> Okay i will do that in new PR , Because this take some time and i also have to re structure the code base from start to end , so better you merge this pr with main branch and tommorow i will open an new issue you just approve it, is it fine.

I have merged the previous PR , have u raised a new issue what @itsekta ma'am has already suggested u ?? if not please raise it so that u will get assigned

**Comment by AbheetHacker4278** [comment]
> > > Hey, @AbheetHacker4278 can you also make it responsive for mobile screen as well
> > 
> > 
> > > Hey, @AbheetHacker4278 can you also make it responsive for mobile screen as well
> > 
> > 
> > Okay i will do that in new PR , Because this take some time and i also have to re structure the code base from start to end , so better you merge this pr with main branch and tommorow i will open an new issue you just approve it, is it fine.
> 
> I have merged the previous PR , have u raised a new issue what @itsekta ma'am has already suggested u ?? if not please raise it so that u will get assigned

Okay , in 2 days i will do it , because my exams are starting , so after that i will do it

**Pull request merged**
