### PR TITLE
feat: Added functionality to Login button

### LINKED ISSUE #764: Log in button redirects to log in page
**Describe the bug**
The user is redirected to the log in page after logging in

**Expected behavior**
User should be redirected to the home page

**Screenshots (Mandatory)**

https://github.com/apu52/Travel_Website/assets/142666229/0419844c-2462-4b46-8863-ae6301b00f9d

**Additional Context (Mandatory )**

GSSoC'24

### PR DESCRIPTION
**Pull request by samarsajad**
# Title and Issue number 

Title :

Issue No. : #764 

Code Stack : 
html
css
javaScript

Close #764

# Description
The login button was not functional. Now it successfully redirects to  the homepage

# Video/Screenshots (mandatory)

https://github.com/apu52/Travel_Website/assets/142666229/579d542c-1bac-470b-9a9d-eeb43065f5bb

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

# Additional context:
GSSoC'24

##Are you contributing under any Open-source programme?

GSSoC'24

### CODE REVIEW

**Comment by samarsajad** [comment]
Please review my pull request @apu52

**Review by apu52 — CHANGES_REQUESTED** [review]
@samarsajad there is some recent changes in the website page so that your PR is facing some merging conflicts . so I would like to request you to submit a new PR making a new branch in your forked PR to avoid all of the conflicts
Otherwise the features u have added are working well .I have checked it

**Comment by samarsajad** [comment]
Can you please suggest what changes you want me to make @apu52

**Comment by samarsajad** [comment]
> @samarsajad there is some recent changes in the website page so that your PR is facing some merging conflicts . so I would like to request you to submit a new PR making a new branch in your forked PR to avoid all of the conflicts Otherwise the features u have added are working well .I have checked it

I created a new PR  #924 as requested. Please check it out @apu52

**Pull request closed without merging**
