### PR TITLE
fix: Added the translate button

### LINKED ISSUE #1437: [Bug]: "Select Language" Dropdown Misplacement and Poor Accessibility
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The "Select Language" element is poorly positioned and lacks prominence. Its placement at the bottom of the footer is not intuitive, making it harder for users to locate. Additionally, the dropdown design does not stand out visually and blends into the page, negatively affecting usability.

### Expected behavior

1. The "Select Language" feature should be replaced with a button that is always present on the right side of the screen, allowing users to easily access it from any page.
2. The button should stand out visually, using a contrasting color or icon that makes it easily noticeable and accessible across different screen sizes.
3. The design should focus on improving usability, ensuring that users can quickly find and switch languages without having to scroll or search for the option.

### Add ScreenShots

image

### On which device are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by CodeMosaic7**
# Title and Issue number 

fix: "Select Language" Dropdown Misplacement and Poor Accessibility

Issue No. : #1437 

Code Stack : 

Close #1437 

# Description

Replaced the google translate widget with a button which on hovering will open widget to translate the website.

# Video/Screenshots (mandatory)

image
On hovering
image
Choosing the language
image

# Type of PR

- [ X] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X ] I have performed a self-review of my code.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have gone through the  `contributing.md` file before contributing
- [X ] I have Starred the Repository.

# Additional context:

##Are you contributing under any Open-source programme?

- [X ] I am contributing under `GSSOC'24 Extended`
- [ ] I am contributing under `Hacktoberfest'24`

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@CodeMosaic7 this pr has merge conflicts , please try to resolve this

**Comment by CodeMosaic7** [comment]
> @CodeMosaic7 this pr has merge conflicts , please try to resolve this

Resolved the conflicts.

**Review by apu52 — CHANGES_REQUESTED** [review]
@CodeMosaic7 

image

the total project messed up after your commit
Please try to do one thing , close this pr for now , try to make a new branch on your forked pr , then try to push all of your changes there & then make a new pr

**Comment by CodeMosaic7** [comment]
I'll try to figure out why that is happening and will generate a pull request.

**Pull request closed without merging**
