### PR TITLE
feat: Made navbar Uniform accross all pages

### LINKED ISSUE #1422: [Bug]: Inconsistent Navbar Styling Between Homepage and Dedicated Destination Pages
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 The navbar on the homepage and the dedicated-destinations pages shows inconsistencies in:

Font Style: Navbar link fonts differ.
Background Color: Navbar background colors are not uniform.
Logo Font: The logo is not present in dedicate-destinations pages.
Button Alignment: Buttons are misaligned across the dedicate-destinations pages..

### Expected behavior

The navbar styling should remain consistent across all pages, including the homepage and the dedicated-destinations page.

### Add ScreenShots

home and other pages: 
Screenshot 2024-10-04 181458
dedicated-destinations pages: 
Screenshot 2024-10-04 181444

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by shivam8112005**
# Title and Issue number 

Title :Consistent Navbar Styling across all pages

Issue No. : #1422 

Code Stack : html, CSS

Close #1422 

# Description

The navbar on the homepage and the dedicated-destinations pages shows inconsistencies in:

Font Style: Navbar link fonts differ.
Background Color: Navbar background colors are not uniform.
Logo Font: The logo is not present in dedicate-destinations pages.
Button Alignment: Buttons are misaligned across the dedicate-destinations pages..

# Video/Screenshots (mandatory)

Screenshot 2024-10-23 162110

# Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing
- [X] I have Starred the Repository.

# Additional context:

##Are you contributing under any Open-source programme?

- [X] I am contributing under `GSSOC'24 Extended`
- [X] I am contributing under `Hacktoberfest'24`

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@shivam8112005 this pr is facing some merge conflicts please try to resolve this so that I can review & merge this pr

**Comment by shivam8112005** [comment]
ohk i will do it by tomorrow

**Comment by shivam8112005** [comment]
hey @apu52  now cnay you merge it?

**Review by apu52 — APPROVED** [review]
@shivam8112005 okkk great

**Pull request merged**
