### PR TITLE
new loginpage

### PR DESCRIPTION
**Pull request by heypriyak**
# Title and Issue number 

Title :

Issue No. :

Code Stack : 

Close #<issue_no>

# Description

# Video/Screenshots (mandatory)

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@heypriyak please fill up the PR properly , otherwise I can't assign you points . I am closing the PR as unplanned

**Comment by heypriyak** [comment]
i changed login page

**Comment by apu52** [comment]
> i changed login page

Can you please tell me what is your assigned issue no. ??

**Comment by heypriyak** [comment]
i dont know

**Comment by apu52** [comment]
> i dont know

As per the rule if the repo , U at first have to raise one issue , & only after get assigned , u can start working on the PR , 
Please go through CONTRIBUTING.md file before contributing in the repo.

**Comment by heypriyak** [comment]
okayy

**Pull request closed without merging**
