### PR TITLE
plantrip , about page (add-ups) and navbar responsiveness

### PR DESCRIPTION
**Pull request by Leorasaharia**
Responsiveness of the **plantrip area**, **navbar** area was made responsive for small devices as i mentioned in my issues, also enhanced the looks and the writeup part of **about sectionin** the website was successfully made #316

Title : Responsiveness of the website, adding an about section, navigation bar upgradation. #316

Issue No. : #316 

Close : #316 

Code Stack :  html, css

i've successfully completed all the issues mentioned in my issue number #316 

# Video/Screenshots (mandatory)

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

***Are you contributing under any Open-source programme?***

1)studdybuddy (ui/frontend)
2) motorsports (ui/frontend)
gssoc:
3) Emowell 
4)Wife-predictor-v2
5)vedic vani
6) draw-it-out
7)chat-box

### CODE REVIEW

**Comment by apu52** [comment]
@Leorasaharia Thanks for the contribution . I will merge/review this PR after successful completion of all the issues you have mentioned.
Just I want to suggest you to attach a video with the PR after successful completion of code contribution to make it more understanding

**Review by apu52 — COMMENTED** [review]
@Leorasaharia Thanks for the contribution . I will merge/review this PR after successful completion of all the issues you have mentioned. Waiting for your contributions
Just I want to suggest you to attach a video with the PR after successful completion of code contribution to make it more understanding

**Comment by Leorasaharia** [comment]
okay i'm on it, just a bit cluttered with other tasks too, i will get back to you as well

**Review by Leorasaharia — COMMENTED** [review]
changed the about section a bit, added a hover effect when one hovers over the written texts in the about section also made the navbar responsive for the small devices.

**Review by Leorasaharia — COMMENTED** [review]
please review my changed @apu52

**Review by apu52 — APPROVED** [review]
@Leorasaharia Good work

**Pull request merged**
