### PR TITLE
BUG : New video Fixed (#151)

### LINKED ISSUE #151: BUG : New video
**Describe the bug**

hello All, 
There was a video in the "Watch our story" section. but somehow it got removed.

**Expected behavior**

#126 refer to the PR & make the same changes in this issue & make a new PR making the changes

**Screenshots (Mandatory)**

**Additional Context (Mandatory )**
### 
### Those who want to work on this issue comment down with JWOC mentioned on it .

***Are you contributing under any open-source program ?***

JWOC'24

### PR DESCRIPTION
**Pull request by vishal2005025**
# Title and Issue number 

Title : New Video #151 

Issue No. : 151

Code Stack : HTML ,CSS

Close #151 

# Video/Screenshots (mandatory)

https://github.com/apu52/Travel_Website/assets/146833908/e18f9cc7-0e79-406d-8eca-9a9a3629ad8e

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**
1. Change the name of new video for proper working .
2. Updated the story.html.
3. Updated CSS in styles.css to fix the video button on index.html and also correctly display the video.

***Are you contributing under any Open-source programme?***

Contributing under JWOC

### CODE REVIEW

**Comment by vishal2005025** [comment]
Name : Vishal Malyan

**Comment by vishal2005025** [comment]
sir , please merge ..

**Review by apu52 — APPROVED** [review]
OK

**Comment by vishal2005025** [comment]
sir, sorry for late reply  Please change the label of this issue to hard as I have work hard to understand the code and spent almost 2 days to fix it.
please change please...

**Comment by apu52** [comment]
> sir, sorry for late reply Please change the label of this issue to hard as I have work hard to understand the code and spent almost 2 days to fix it. please change please...

Sorry @vishal2005025 But This PR seems to have the MEDIUM label. I can't label it HARD. But Hope to see many of your contributions in this repo.

**Pull request merged**
