### PR TITLE
Added Rating System 

### LINKED ISSUE #48: {Feature_Request}  Rating system using HTML CSS
I want to add a rating system
**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
Ss1
Ss2

Contributing under JWOC

### PR DESCRIPTION
**Pull request by daksh1210jain**
# Title and Issue number 

Title : Rating system using HTML CSS 

Issue No. : #48 

Code Stack : HTML CSS JAVASCRIPT

Close #48 

# Video/Screenshots (mandatory)

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.

https://github.com/apu52/Travel_Website/assets/137384322/3cc18140-7cb1-456b-9d21-9d2185920564

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***
 under JWOC

### CODE REVIEW

**Comment by apu52** [comment]
@daksh1210jain This PR has merge conflicts . I want to suggest you to close this PR & update your branch in the forked repo & then submit your PR

**Comment by daksh1210jain** [comment]
sir kindly have a look i have resolved all the conflicts

**Review by apu52 — APPROVED** [review]
OK

**Comment by apu52** [comment]
@daksh1210jain Can you pleas share your full name so that I can update the LEADERBOARD

**Pull request merged**
