### PR TITLE
feat: ✔️Added Vertical Scrollbars to ALL ABSENT Pages !

### LINKED ISSUE #1371: BUG🐞: Add Custom Scrollbar Styling to ALL the Missing Pages !
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @apu52 and @itsekta ,

On the website, the Terms and Conditions, Licensing,Privacy Policy, Blogs, Contributors, and several other pages currently display the default vertical scrollbar. 
However, the rest of the website's pages feature a custom-styled vertical scrollbar that enhances the visual consistency and user experience.

### Expected behavior

A custom-styled vertical scrollbar enhances the visual consistency and user experience.

### Add ScreenShots

****Here as you can see-****

https://github.com/user-attachments/assets/b4fa224a-d7fd-4595-9e5b-c36e83b50a7b

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Tejashri-Taral**
Hey @apu @itsekta 
issue closes #1371

I have added Custom Scrollbar in all the absentpages of website 
earlier it was absent in the page which were not following the consistency.

https://github.com/user-attachments/assets/c3139522-967f-4f94-96df-6ee5f124d222

PLease take a look.
thankyou!

# Type of PR
- [x] Feature enhancement
# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24`

### CODE REVIEW

**Comment by Tejashri-Taral** [comment]
@apu52 Please review it.

**Comment by Tejashri-Taral** [comment]
@apu52 and @itsekta Plaese merge it

**Comment by Tejashri-Taral** [comment]
@apu52 and @itsekta Please merge it

**Comment by apu52** [comment]
@Tejashri-Taral this PR has some merge conflicts .Please try to resolve the conflicts ASAP before 7 pm

**Comment by Tejashri-Taral** [comment]
@apu52 Please Check now

**Review by apu52 — APPROVED** [review]
@Tejashri-Taral good work

**Pull request merged**
