### PR TITLE
fix: issue is resolved

### PR DESCRIPTION
**Pull request by Aditya90456**
now back to home

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@Aditya90456 the pr form is not correctly filled up .Please try to fill the pr form correctly with all of the details (e.g the issue no. , the features u have added , prototype videos/images etc.) please try to modify your pr with this so that I can merge this pr.

**Comment by Aditya90456** [comment]
i solved issue @apu52 
https://github.com/user-attachments/assets/9575ba18-4cce-42df-8054-4bca459ab9fe

**Comment by apu52** [comment]
> i solved issue @apu52 https://github.com/user-attachments/assets/9575ba18-4cce-42df-8054-4bca459ab9fe

Like the changes in the website is not properly shown in the website . Please try to make the video properly & also fill the form up like the details 
1. issue no.
2. in which open source programme u are contributing 
3. the proper prototype video /ss of your changes 

u can take reference from the other PR's format .please check that

**Review by Aditya90456 — COMMENTED** [review]
no.issue is #1521
I am contributor of GirlScript summer of code

https://github.com/user-attachments/assets/14fef43b-104d-44e0-9ce5-9f868288d2a4

**Review by apu52 — APPROVED** [review]
@Aditya90456 good work really great

**Pull request merged**
