### PR TITLE
New navbar 

### LINKED ISSUE #221: STYLE Navbar improvement
**Describe the bug**
Updated navbar 

**Screenshots (Mandatory)**

Current navbar 
https://github.com/apu52/Travel_Website/assets/125949765/443116be-712e-4cdc-9ed7-af27be247e4c

Changes 
               1.order of navbar option 
               2. Change dark mode button 
New navbar 

https://github.com/apu52/Travel_Website/assets/125949765/1232cfc1-d5af-489b-abc6-e1eb43ab0c75

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

jwoc

### PR DESCRIPTION
**Pull request by AftabMankapure**
# Title and Issue number 

Title : Style navbar improvement 

Issue No. : #221 

Code Stack :  

Close #221 

# Video/Screenshots (mandatory)

https://github.com/apu52/Travel_Website/assets/125949765/1232cfc1-d5af-489b-abc6-e1eb43ab0c75

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

jwoc

### CODE REVIEW

**Comment by AftabMankapure** [comment]
pls merge fast i want work on dark mode them #207

after merge this issue it is easy to work on this issue

**Comment by AftabMankapure** [comment]
so pls merge this first

**Comment by apu52** [comment]
@AftabMankapure please follow the rules mentioned in `contributing.md` file .Don't make any type of PR until & unless you get assigned.

**Comment by apu52** [comment]
@AftabMankapure Please follow the rules mentioned in `contributing.md` file . Please don't make any PR until & unless you get assigned to any issue

**Pull request closed without merging**
