### PR TITLE
fix: Issue #928 #915 fixed BUBBLE File commented and Blogs with trending section added

### LINKED ISSUE #915: [Feature Request]: ADDITION OF "TRENDING"SECTION OR "IN DEMAND" SECTION
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Tours which are currently in demand can be showcased on the site with buttons that can be linked to Blogs Created by customers which bought that tour. 

### Use Case

It would be easy for people to find a tour currently in trends.

### Benefits

FEATURES:
Enhanced Visibility: Showcase currently in-demand tours prominently on your site to attract visitor attention.
Customer Engagement: Link these tours directly to customer-created blogs, fostering trust and interest through authentic experiences.
Conversion Optimization: Use direct links to customer blogs to demonstrate real-life experiences, boosting conversion rates by offering genuine testimonials and insights.

### Add ScreenShots

WhatsApp Image 2024-06-25 at 20 32 00_f2df4489
JUST LIKE THIS WITH ENHANCED FEATURES AND BUTTONS.

@apu52 Please assign me this issue under GSSOC 24.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### LINKED ISSUE #928: Remove the bubbles animation from the landing page[Bug]:
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The **bubbles** on the landing page are not good for user experience. Remove these and keep it in separate file if needed can be added later to another section

image

### Expected behavior

The landing page will look more nice without these bubble animations.

### Add ScreenShots

_No response_

### On which device are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by taniya542**
# Title and Issue number 

Title :
Issue No. #915 
Issue No. : #928 

Code Stack : 

Close #928
close #915 
Bubble file CSS commented,if needed can be used later.

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [/x] Documentation update
- [/x] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

# Additional context:

- [x] I am contributing under `GSSOC'24`
- [cross/X] I am contributing under `VSOC'24`
 I have added Trending Button in Tours section.
WhatsApp Image 2024-06-28 at 22 23 49_07b520d9
This will open up List of trending tours as shown below.Cards are used here with hover effects and background also includes motion. Each trending tour is connected with A Blog Page where a person can read blogs related to that tour.
WhatsApp Image 2024-06-28 at 22 26 00_1320247d
WhatsApp Image 2024-06-28 at 22 26 41_8c643a40

Explore more button is connected to site where more tours are available and is functional.While on clicking the Blog button a person is directed to a blog page. for ex: clicking on varanasi one:
image
WhatsApp Image 2024-06-28 at 22 29 09_13030a7f
WhatsApp Image 2024-06-28 at 22 29 47_33d0c5bc
After a long Blog there is a contact section also. Blog pages also include hover effects and lots of images.

image

https://github.com/apu52/Travel_Website/assets/143064148/5ce238bf-3359-4bf6-bea5-c79e97b4c70a

### CODE REVIEW

**Comment by taniya542** [comment]
@itsekta Please review this PR.

**Review by itsekta — APPROVED** [review]
Commented bubble code. Ready to be merged

**Comment by taniya542** [comment]
@itsekta @apu52 Please review the changes and merge my PR.

**Review by apu52 — CHANGES_REQUESTED** [review]
@taniya542 @itsekta have already reviewed your trending page PR & the page looks really cool

But why these bubble animation changes belongs in this PR as this issue is not assigned to u .It is already assigned to another contributor. Please do all the changes in which issue you are only assigned

**Comment by apu52** [comment]
@taniya542 I want to request you to please remove #928 issue from your PR form as well as all the changes u have made regarding that issue in this issue .otherwise I can't merge this PR . Otherwise u can submit a new OR with only the changes of the #915 issue

**Comment by taniya542** [comment]
@apu52 Can I raise a new PR for this?

**Comment by apu52** [comment]
> @apu52 Can I raise a new PR for this,actually when I started working on issue 928 it wasn't assigned to anyone?

yess you can . & if u are submitting a new PE . can I now close this pR??

**Comment by taniya542** [comment]
@apu52 I have made a new PR regarding this issue.Please review it

**Pull request closed without merging**
