### PR TITLE
feat: Enhanced styling of packages page

### LINKED ISSUE #1610: [Feature Request]: Enhanced Styling for Packages Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The proposed enhancement aims to improve the overall aesthetics and usability of the Packages page within our application. Currently, the page does not effectively showcase the available packages, leading to a suboptimal user experience. The new design will focus on creating a visually appealing layout, incorporating modern UI/UX principles to facilitate user interaction and engagement.

### Use Case

Imagine a potential customer browsing our application to find the perfect package for their needs. They arrive at the Packages page, which currently presents information in a dense and unorganized manner. By implementing the enhanced styling, the user will be greeted with an organized grid of visually distinct package cards, making it easy to scan through options.

The user can quickly identify key features at a glance and click on a package that catches their interest. The clear call-to-action buttons will direct them to further details, and the inclusion of user reviews will provide additional context and assurance, ultimately increasing the likelihood of purchase.

### Benefits

Improved User Experience: The new design will significantly enhance user satisfaction by providing a visually engaging and intuitive interface, making it easier for users to find and evaluate packages.

Increased Engagement: An organized and appealing layout will encourage users to spend more time on the Packages page, exploring various offerings rather than quickly leaving due to frustration with the existing design.

Higher Conversion Rates: By making the decision-making process smoother and more enjoyable, we can expect to see an increase in conversions, as users are more likely to purchase packages that are presented attractively and clearly.

Community Trust: User reviews and ratings foster trust and transparency, encouraging more users to consider purchasing packages, knowing they can rely on feedback from others.

Brand Recognition: A well-styled Packages page contributes to a professional image of our application, reinforcing brand identity and recognition among users.

### Add ScreenShots/Videos

Screenshot 2024-11-01 015243

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by shivam8112005**
# Title and Issue number 

Title : Enhanced styling of packages page

Issue No. :  #1610 

Code Stack :  html, css

Close #1610 

# Description

This PR introduces a comprehensive redesign of the packages page to improve the overall user experience and visual appeal. The new styling enhances readability and interaction, making it easier for users to navigate and understand package details.

# Video/Screenshots (mandatory)

https://github.com/user-attachments/assets/7e46bf85-d507-46a8-8fb1-840bd0026285

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing
- [X] I have Starred the Repository.

# Additional context:

##Are you contributing under any Open-source programme?

- [X] I am contributing under `GSSOC'24 Extended`
- [X] I am contributing under `Hacktoberfest'24`

### CODE REVIEW

**Comment by shivam8112005** [comment]
@apu52  is it ok ?

**Review by apu52 — APPROVED** [review]
@shivam8112005 Although the UI of the packages pg can be better , still Good efforts , Thanks for your valuable contribution

**Comment by apu52** [comment]
@shivam8112005 u can make a better ui by maybe adding some additional package cards , like some interesting professional type package cards as well ass some more detailed description about the tour packages as well as some maybe good UI

**Comment by shivam8112005** [comment]
ohkk got it just tell me which type of images should i add in package cards?

**Comment by apu52** [comment]
> @apu52 ohk got it just tell me which type of images should i add in package cards? and i will open an issue for it

yess , open a new issue on it & add images according to the package like tour packages like some discount & all maybe signify it with different type of colors

**Comment by shivam8112005** [comment]
@apu52  ohk i am opening new issue

**Pull request merged**
