### PR TITLE
Fixed Slow Hover Transition Effect on Trip Cards issue #433

### LINKED ISSUE #433: BUG
Bug Description: Slow Hover Transition Effect on Trip Cards
Issue Summary:
The hover effect on the trip cards is currently transitioning too slowly, resulting in a less responsive and less user-friendly experience. which makes the hover effect sluggish. Additionally, the cursor changes to a zoom-in style, but it would be more intuitive to change it to a pointer style to indicate interactivity.

Could you please assign this issue to me so I can work on it as part of GSSOC 2024?

### PR DESCRIPTION
**Pull request by RohithChitrada**
# Title and Issue number 

Title :Slow Hover Transition Effect on Trip Cards

Issue No. : #433 

Code Stack : CSS, HTML

Close #433 

# Video/Screenshots (mandatory)

https://github.com/apu52/Travel_Website/assets/120176158/27be9793-2296-4701-b9f3-dfb0b625841c

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***
GSSOC'24

### CODE REVIEW

**Comment by RohithChitrada** [comment]
I have resolved the merge conflicts. Try to merge it know

**Comment by apu52** [comment]
> I have resolved the merge conflicts. Try to merge it know

@RohithChitrada some checks are not checked yet.

**Comment by RohithChitrada** [comment]
Know you can merge it.

**Review by apu52 — APPROVED** [review]
@RohithChitrada Good work

**Pull request merged**
