### PR TITLE
feat: Added Cookie Pop-up to the Website

### LINKED ISSUE #1126: [Feature Request]:  Add Cookie Pop-up to the Website
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a cookie pop-up to the website. This pop-up will inform users about the use of cookies on the site, request their consent, and provide a link to the privacy policy. The pop-up should be designed to match the website's theme and aesthetics to ensure a consistent user experience.

### Use Case

Adding a cookie pop-up will enhance the website by ensuring compliance with data protection regulations. It will also increase transparency with users regarding data usage, which can build trust and improve user experience.

### Benefits

A user visits the website for the first time. The cookie pop-up informs them about the use of cookies and asks for their consent. 

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by TBorundia**
# Title and Issue number 
Title : Added Cookie Pop-up to the Website

Issue No. : #1126

Code Stack : 

Close  #1126

# Description
Added Cookie Pop-up to the Website, included the paragraph to understand the concept.
It is responsive too

# Video/Screenshots (mandatory)

https://github.com/user-attachments/assets/8244b4cb-a467-4e99-a773-97f6e8d7a1f4

Screenshot 2024-07-24 182733

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X]  I have performed a self-review of my code.
- [X]  I have commented my code, particularly in hard-to-understand areas.
- [X]  I have tested the changes thoroughly before submitting this pull request.
- [X]  I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X]  I have gone through the  `contributing.md` file before contributing

##Are you contributing under any Open-source programme?
- [X]  I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by TBorundia** [comment]
@apu52 , please review this PR.
As @itsekta has said , it will be assign to me after completing my previous issues.
Thank You!

**Comment by itsekta** [comment]
The card UI looks very good. Just a small improvement: currently, it is hiding the back-to-top button. Could you try to position the cookies card somewhere else?

**Comment by TBorundia** [comment]
> Hey @TBorundia, The card UI looks very good. Just a small improvement: currently, it is hiding the back-to-top button. Could you try to position the cookies card somewhere else?

@itsekta ,
Can you suggest where should I placed that card ?
As at right side there is chatbot option and left side back to top button.
Should I place it at middle?

**Comment by TBorundia** [comment]
@itsekta @apu,

image

Please review it now

**Review by apu52 — APPROVED** [review]
@TBorundia it's looking really well well made changes

**Comment by apu52** [comment]
@itsekta ma'am can u please also check the changes ??
So that I can merge it.

**Comment by TBorundia** [comment]
@apu52 Please review and merge this PR , So that I can start working on another issue.

**Review by itsekta — APPROVED** [review]

**Comment by itsekta** [comment]
@apu52, this PR is good to go

**Comment by TBorundia** [comment]
@apu52 , Please merge this PR as it is approved.

**Comment by TBorundia** [comment]
@apu52  , Please merge this PR as it is approved.

**Pull request merged**
