### PR TITLE
Shivam's nav bar

### LINKED ISSUE #25: BUG : Make the Navbar Dynamic & Reasponsive
**Describe the bug**

Hello all,
The Navbar is not responsive at all . you can make it as a Responsive & dynamic & can add some CSS cool styling to it

**Expected behavior**

It will help all the users of the website to use this website well.

**Screenshots (Mandatory)**

image

**Additional Context (Mandatory )**

Comment down if you want to work on this issue. Whoever comments first , I will assign the issue to her/him first.

***Are you contributing under any open-source program ?***

JWOC 2k24

### PR DESCRIPTION
**Pull request by SGCODEX**
BUG Report : Make the Navbar Dynamic & Reasponsive #25 & #35

Title : Improved NavBar(logo & button too), Made it Responsive and resizable

Issue No. :#25 & #35

Code Stack : HTML, CSS

Close #25 

# Video/Screenshots
https://github.com/apu52/Travel_Website/assets/64886313/365f9424-0562-4f69-ac62-b39d43c8ac61

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**
I have made many changes to the NavBar and made it Responsive and better
I have made the scrolling in the program as smooth
I have done the internal linking with the Navbar
I have made Nav Bar somewhat resizable
I have made the button of Contact us also a <a> link because earlier it was only redirecting on clicking on the text, now whole button works as a link
I have internal referenced with sections
Edit - I have also covered up the issue #35 now and connected the Contact Us Button to Admin's LinkedIn

In CSS
I have made all the text and button as bold on hovering
I have fixed the Nav Bar so that scrolling is easy through any part of the webpage
I have made logo bigger on hovering
and made some minor changes here and there

I have done a lot more than just making the NavBar Responsive, I would request you sir to kindly make this issue as Medium from Easy and accept my PR

Thank You

Issue Faced:
The Website is heavy and sometimes lags, I figured out this issue might me because of Heavy images, requesting to create an issue for the same.

***Are you contributing under any Open-source programme?***
JWOC

### CODE REVIEW

**Comment by apu52** [comment]
@SGCODEX Please try to resolve the merging conflicts

**Review by apu52 — CHANGES_REQUESTED** [review]
MERGE CONFLICTS

**Comment by SGCODEX** [comment]
Sir now it is okay?

**Review by apu52 — APPROVED** [review]
OK

**Pull request merged**
