### PR TITLE
feat: ✔️Implemented Dynamic "Last Updated" Functionality to All Legal Pages !

### LINKED ISSUE #1304: 🌟 Add Dynamic "Last Updated" Functionality to All Legal Pages !
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @apu52 and @itsekta 

I want to add a **"Last Updated: " functionality** to the legal pages of our website, specifically the **Privacy Policy, Terms and Conditions, and Licensing pages**. 
This functionality **will be dynamically adjustable to update monthly and yearly.**

**I will use Javascript Scripts to make this implementation**

Please Refer to the attached image **for an example** of how the functionality should look

image

<hr>

**Currently, The Legal Pages Do not have these Updates, Which makes user feel Outdated.**

image

image

I want to work on this, please assign me.
thankyou 

### Use Case

**Monthly Update for Privacy and Terms Pages:**
At the start of a new month, the system automatically updates the date on the Privacy page to reflect the current month and year (e.g., "Last updated: August 2024").

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @apu52 @itsekta 
issue closes #1304 

I have implemented a dynamic "Last Updated" date feature for the legal pages on the website, including the Terms and Conditions and Privacy Policy pages.

The **date format** is set to **"Month Day, Year"** and will update dynamically to reflect the current date. 
**Additionally, "each page has a specific update frequency" to ensure the date remains accurate.**

**Changes Made :** 
- Added a script to dynamically update the "Last Updated" date for the Terms and Conditions, Privacy Policy, and Licensing pages.
- The **date format** is **"Month Day, Year" for a professional appearance.**

**Here -**
image

image

image

# Type of PR

- [x] Feature enhancement

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24`

### CODE REVIEW

**Comment by aslams2020** [comment]
@apu52

**Comment by aslams2020** [comment]
@apu52 Please review it

**Comment by aslams2020** [comment]
@apu52 Please review it

**Review by apu52 — APPROVED** [review]
@aslams2020 good work

**Pull request merged**
