### PR TITLE
fix: fixed mobile view of home page

### LINKED ISSUE #790: BUG fixing css of home page in mobile view
**Describe the bug**

Css of home page in mobile view is not working properly 

**Expected behavior**

Making home page responsive 

**Screenshots (Mandatory)**

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

Yes gssoc and ssoc

### PR DESCRIPTION
**Pull request by dhairyagothi**
# Title and Issue number 

Title : BUG fixing css of home page in mobile view  

Issue No. : #790 

Code Stack : 

Close #790 

# Description

# Video/Screenshots (mandatory)

before:
image

after:
image

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@apu52  please merge this PR

**Comment by dhairyagothi** [comment]
@apu52 Please check PR and merge it

**Comment by dhairyagothi** [comment]
@apu52 please merge the PR with gssoc label

**Review by apu52 — CHANGES_REQUESTED** [review]
@dhairyagothi  there is some recent changes in the website page so that your PR is facing some merging conflicts . so I would like to request you to submit a new PR making a new branch in your forked PR to avoid all of the conflicts
Otherwise the features u have added are working well .I have checked it

**Comment by dhairyagothi** [comment]
Okay i will make

**Comment by dhairyagothi** [comment]
done @apu52 check it

**Review by apu52 — APPROVED** [review]
@dhairyagothi good work

**Pull request merged**
