### PR TITLE
fix: newLogin.html

### PR DESCRIPTION
**Pull request by CoderGirl2844**
Title : Add favicon to the login page

Issue No. : https://github.com/apu52/Travel_Website/issues/873

Code Stack : html

Close https://github.com/apu52/Travel_Website/issues/873

Description
After reviewing the newLogin.html file the favicon file was not linked correctly

Screenshots (mandatory) :

Screenshot 2024-07-04 104713

Type of PR :
updated the html file

Checklist:
I have performed a self-review of my code.
I have commented my code, particularly in hard-to-understand areas.
I have tested the changes thoroughly before submitting this pull request.
I have provided relevant issue numbers, screenshots, and videos after making the changes.
I have gone through the contributing.md file before contributing

Additional context:
I am contributing under GSSOC'24

### CODE REVIEW

**Comment by CoderGirl2844** [comment]
please review my PR

**Comment by apu52** [comment]
@CoderGirl2844 this pR form is not filled up correctly .there is already a PR template present in this project . please try to use that to submit your pR with all the proper details filled into it. otherwise I can't be able to review your PR

**Review by apu52 — CHANGES_REQUESTED** [review]
what are the changes ???? I can't see any valuable changes

**Comment by CoderGirl2844** [comment]
@apu52 I have made the changes and inspected it too please merge my PR

**Comment by apu52** [comment]
@CoderGirl2844 this pR has some merge conflicts , I want to suggest you to submit a complete new pr on this issue to avoid all the conflicts.

**Pull request closed without merging**
