### PR TITLE
Added new Login Page and Registration page 

### LINKED ISSUE #528: BUG: LogIN screen's  login button doesn't work
**Describe the bug**

Login page's login button doesn't work

**Expected behavior**

the pressing of Login Button will take you to a login page .

**Screenshots (Mandatory)**

image

**Additional Context (Mandatory )**
the register portion also doesn't work
***Are you contributing under any open-source program ?***

GSOC24

### PR DESCRIPTION
**Pull request by Tasnuva12**
I modified the existing page's code and  added new login and registration page

# Title and Issue number 

Title : LogIN screen's login button doesn't work

Issue No. :#528

Code Stack : 

Close #528

# Video/Screenshots (mandatory)

https://github.com/apu52/Travel_Website/assets/47001609/e7c69245-f7e9-4733-9837-c791fc51ccf3

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

Girls Script Summer Code 2024

### CODE REVIEW

**Review by apu52 — APPROVED** [review]
@Tasnuva12 your changes are really impressive

**Comment by apu52** [comment]
@Tasnuva12 but I want to suggest you that as per your changes can you make a different LOGIN page (whenever the user press the LOGIN button she/he will be redirected to that page) 
If you can make this in this PR that will be great , please respond otherwise I can still merge this PR

**Comment by Tasnuva12** [comment]
Hello, I did not understand your request. I implemented that when someone will press the login button of the  topbar, the login page will be opened. Do you want me to modify my login page?

**Comment by apu52** [comment]
> Hello, I did not understand your request. I implemented that when someone will press the login button of the topbar, the login page will be opened. Do you want me to modify my login page?

okay no problem . You don't have to do farther changes . I am merging this PR

**Review by apu52 — APPROVED** [review]
Okay

**Pull request merged**
