### PR TITLE
feat: Resolved the issue of the hamburger #1582

### LINKED ISSUE #1512: No hover effect on 2nd button of home page ie. plan a trip
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @apu52 please assign me this task (#1512) so that I can start working on this.
https://apu52.github.io/Travel_Website/
At home page out of 3 button on 2nd button their is no hover effect .

### Expected behavior

As every button is having hover effect then 2nd one should also has the same hover effect

### Add ScreenShots

https://github.com/user-attachments/assets/90016730-3173-4e48-a320-bc6c1ed3d9a1

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by shriyadindi**
Title : Resolved the issue of the hamburger

Issue No. : #1518 

Close #1512 

Code Stack : HTML, CSS, JS

# Video/Screenshots (mandatory)

https://github.com/user-attachments/assets/36113849-fbb1-486f-b51e-9f1b1115438f

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have gone through the  `contributing.md` file before contributing
- [ ] I have Starred the Repository.

# Additional context:

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24 Extended`
- [ ] I am contributing under `Hacktoberfest'24`

### CODE REVIEW

**Review by apu52 — APPROVED** [review]
@shriyadindi 
image

though there are some bugs but still I am merging this pr , 
please try to make a separate pr fixing this bug on this issue

**Comment by apu52** [comment]
@shriyadindi btw great work. really great dedication

**Comment by shriyadindi** [comment]
@apu52 Thank you!

**Comment by shriyadindi** [comment]
@apu52 I'll to resolve them.

**Comment by shriyadindi** [comment]
@apu52 I've worked in the bug of the navbar.
https://github.com/apu52/Travel_Website/pull/1589

**Pull request merged**
