### PR TITLE
[ISSUE - 38] Top destination slider

### LINKED ISSUE #38: Feature_Request : Top destination slider
**Is your feature request related to a problem? Please describe.**
In the Explore top destinations section of websites, there are arrow slide buttons that are not working and images aren't aligned that look cool in the website preview. 

**Describe the solution you'd like**
I will make the slide arrow buttons work by adding a slideshow of images having the same characteristics just images revolving in the section of 3 images and images will be of the same height and width increasing user impact over the website.

**Describe alternatives you've considered**
I have considered a slideshow of pics so new images can be added easily and they also look cool.

**Demo Video/Screenshot (Mandatory )**

https://github.com/apu52/Travel_Website/assets/147709304/a4d55f3e-03ac-44a2-a567-a1489a4c7598

image

***Are you contributing under any open-source program ?***
Yes under JWOC I am contributing as mentee.

### PR DESCRIPTION
**Pull request by antilneeraj**
## Title

Top Destination slider

## Description

Added the Carousel and the carousel is fully functional whether you click on slider arrows or dots it will slide to next image and also it updates the destination details accordingly.

- Issue No. : #38 

Code Stack :  HTML, CSS, JS

- Close #38 

# Screenshots (mandatory)
image
image

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

***Are you contributing under any Open-source programme?***
I'm Contributing under JWOC.

### CODE REVIEW

**Comment by antilneeraj** [comment]
@apu52 This pull request is ready for review and merge. Additionally, I kindly request you to consider adding the "JWOC" and "Difficulty" labels to this pull request.

**Review by apu52 — CHANGES_REQUESTED** [review]
image

image

image

**Comment by apu52** [comment]
@antilneeraj you slider contribution is really great. But most of the headings & the other writings of the websites are totally invisible in the LIGHT THEME , so I just want you to make the changes in the PR. compare it with the main website

**Comment by antilneeraj** [comment]
@apu52 Ok I'll do that by today

**Comment by antilneeraj** [comment]
@apu52 The `issue` which was occuring with the `headings & subheadings` of various section in `Light Theme is Fixed`. I kindly request you to `re-review` my PR and provide your feedback.

**Review by apu52 — APPROVED** [review]
OK. really great contribution

**Pull request merged**
