### PR TITLE
fix: Login Page responsive

### LINKED ISSUE #1314: [Bug]:  Login Page responsive
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Improvement in UI,
Page is not responsive,

### Expected behavior

image

### Add ScreenShots

_No response_

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by TBorundia**
# Title and Issue number 

Title : Login Page responsive

Issue No. : #1314

Close #1314

# Description
Made the Login Page responsive

# Video/Screenshots (mandatory)

https://github.com/user-attachments/assets/c7d89c56-56eb-4fc4-823b-32457886f7e1

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X]  I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

##Are you contributing under any Open-source programme?

- [X] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by TBorundia** [comment]
@apu52 ,
Please review this PR. Thank You!

**Comment by itsekta** [comment]
Hey @TBorundia, on which login page you have implemented the responsiveness?

**Review by apu52 — APPROVED** [review]
@TBorundia this looks well

**Review by apu52 — CHANGES_REQUESTED** [review]
@TBorundia but why is this commit present in this PR , please remove it & then ping me here

**Pull request closed without merging**
