### PR TITLE
Feedback Page and Login Page is fixed

### LINKED ISSUE #469: Feature_Request:  Added missing Navbar on the feedback page
**Is your feature request related to a problem? Please describe.**

the Navbar was missing in the feedback section  and unable to navigate back so , itis important to add Navbar to feedback page also

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
before screenshot
Screenshot (1692)

after updating

Screenshot (1693)

***Are you contributing under any open-source program ?***
yes girlscript summer of code (Gssoc'24)

### PR DESCRIPTION
**Pull request by SadafKausar2025**
# Feedback Page and Login Page  fixed  and: #469

Title :

Issue No. :#469

Code Stack : 

Close #469 

https://github.com/apu52/Travel_Website/assets/137484958/fe29cfb1-261a-43ec-a261-d58db399f808

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
hello @apu52 
now conflicts are resolved and all set

**Comment by SadafKausar2025** [comment]
hello @apu52 
conflicts are resolved , can you please merge pr

**Review by apu52 — APPROVED** [review]
@SadafKausar2025 good work

**Comment by apu52** [comment]
@SadafKausar2025 sorry for the conflicts you have faced. thanks for the contribution

**Comment by SadafKausar2025** [comment]
I can easily resolved the conflict 
but when you closed the pr then it is not possible to resolve the conflict

**Comment by apu52** [comment]
> I can easily resolved the conflict but when you closed the pr then it is not possible to resolve the conflict

I have already merged the PR. & solved the conflicts myself . So don't worry .just keep up your contributions

**Pull request merged**
