### PR TITLE
feat: Added search bar and price filter in the pricing page 

### LINKED ISSUE #574: adding a search bar and filter in the pricing page
**Is your feature request related to a problem? Please describe.**

I've observed that there isn't a search bar at the top of the pricing page. This means that if I have to search for a particular place, I have to scroll through everything, which hinders a smooth user interface. Also, if users have a particular budget in mind, they have to scroll through all the options to find a fit for their budget. This could be improved for a better user experience.

**Describe the solution you'd like**

A viable solution is adding a standard search bar at the top of the pricing page. This addition would allow users to quickly find specific destinations without having to scroll through the entire list. Along with this implementation of a "sort by" filter would provide users with the flexibility to sort options based on their preferences, such as price or star ratings of a particular place.

**Demo Video/Screenshot (Mandatory )**
This is a simple example of how a search bar and sort-by filter would look like 
Screenshot 2024-05-24 210706
and this is where we could add it on the original page 
Screenshot 2024-05-24 212253

***Are you contributing under any open-source program ?***

Yes, i am a contributor at GSSoC.

Please, assign this task to me. 
And please assign appropriate labels to it.

### PR DESCRIPTION
**Pull request by bhavya-taneja**
# Title and Issue number 

title : adding a search bar and filter in the pricing page

Issue No. : #574

Code Stack : html, css and javascript

Close #574 

# Description

I have added a search-bar and a drop down filter in the pricing page to help users search their desired destinations. 

# Video/Screenshots (mandatory)

https://github.com/apu52/Travel_Website/assets/128042756/d23ffb89-6eb3-41e2-a828-54025a045a88

# Type of PR

 Feature enhancement

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

# Additional context:

Kindly comment if any changes are required.

# Are you contributing under any Open-source programme?

it is a part of (girl script summer of code 2024)GSSOC'2k24

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
image

All the changes are really good & working well but the price filter is misaligning. Please try to resolve the alignment problem so that I can merge this PR as this is a very good feature.

**Comment by bhavya-taneja** [comment]
Thank you!
I have tried to resolve the misalignment issue by switching their positions. The placements were fine on my system, but considering your screenshot, I have done the rectifications at my level. Please check it and let me know if the issue is resolved.
image

**Comment by bhavya-taneja** [comment]
@apu52 kindly check the changes made and do let me know if any other amendments are required....

**Review by apu52 — APPROVED** [review]

**Review by apu52 — APPROVED** [review]
@bhavya-taneja really great work

**Pull request merged**
