### PR TITLE
fix: Footer Section alignment issue fixed

### LINKED ISSUE #906: [Bug]: Footer Section alignment issue
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Elements of footer section are not aligned properly.
Social Media icons are overlapping.
Twitter's old logo has been displayed.
Contact details is displaying in multiple line, that the number must be in 1 line.

### Expected behavior

Enhancement in footer section in required.

### Add ScreenShots

image

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by TBorundia**
# Title and Issue number 
Title : Footer Section alignment
Issue No. : #906

Code Stack : 

Close #906

# Description
1.Alignment issue of the text and links.
2. Icons where displaying twice.
3. Google translator script working .
4. Hovering effect to icons according to there logo.
5. Made the page responsive too.

# Video/Screenshots (mandatory)
Before:
Screenshot 2024-07-04 013705

After:

https://github.com/apu52/Travel_Website/assets/168854094/97798ac0-2679-4b09-817f-c3143a7dce50

Also made is responsive for small screen:
Screenshot 2024-07-04 124440

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X]  I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X]  I have tested the changes thoroughly before submitting this pull request.
- [X]  I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X]  I have gone through the  `contributing.md` file before contributing

##Are you contributing under any Open-source programme?

- [X]  I am contributing under `GSSOC'24`
- [ ]  I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by TBorundia** [comment]
@apu52  @itsekta , please review this PR. Thank You!

**Comment by itsekta** [comment]
Hey @TBorundia, can you also look for this additional space in footer is doesn't looks nice 
image

**Comment by TBorundia** [comment]
> Hey @TBorundia, can you also look for this additional space in footer is doesn't looks nice image

@itsekta ,
which space mam?
The space , beside of 3 lines of header section?

**Comment by TBorundia** [comment]
@itsekta ,
which space mam?
The space , beside of 3 lines of header section?

**Comment by itsekta** [comment]
The white space

**Comment by TBorundia** [comment]
> The white space

Ok mam, I will also solve this issue.

**Comment by TBorundia** [comment]
@itsekta Mam, it is because of the "vertical scroll bar" that is present in right side.
It is not only in footer section but also in whole website, it the space for scroll bar.

**Comment by apu52** [comment]
> > The white space
> 
> Ok mam, I will also solve this issue.

have u done the changes which @itsekta ma'am have already mentioned?? If yes then just reply So that I can review your PR

**Comment by TBorundia** [comment]
@apu52 @itsekta ,
Now I have made the changes that you have asked for and remove the white space at right also.
Please review this PR. Thank You!

**Comment by TBorundia** [comment]
> > > The white space
> > 
> > 
> > Ok mam, I will also solve this issue.
> 
> have u done the changes which @itsekta ma'am have already mentioned?? If yes then just reply So that I can review your PR

@apu52  @itsekta ,
I have made the changes and removed the white space also that mam asked for.
Please review this PR.

**Review by apu52 — APPROVED** [review]
@TBorundia good work

**Pull request merged**
