### PR TITLE
fix: fixed-directing-to-different-pages-from-plan-a-trip-page-and-image-slider-to-stop-when-it-reaches-the-last-image

### LINKED ISSUE #1493: [Feature Request]: Enhancing Plan a trip page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The tabs in the nav bar do not direct to the respective pages. I would like to make changes to make sure they are navigating to the correct pages.
Also in the trip suggestion section the cards move even if there are no further cards containing information. Changing them such that navigation stops after it reaches the last suggestion card would look good.

### Use Case

Improves user experience and easy navigation through the application.

### Benefits

_No response_

### Add ScreenShots

Screenshot 2024-10-11 103537
Screenshot 2024-10-11 103942

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

Please add the tags: hacktoberfest-accepted, hacktoberfest, gssoc-ext

### PR DESCRIPTION
**Pull request by Arveti-likhitha**
Title :  Enhancing Plan a trip page

Issue No. : #1493

Code Stack :  HTML, CSS, JS

Close #1493

# Description

Made changes to make sure they are navigating to the correct pages and changing the image slider such that navigation stops after it reaches the last image card.

# Video/Screenshots (mandatory)

https://github.com/user-attachments/assets/fc8397df-7378-4064-aae0-c859e4efc490

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing
- [X] I have Starred the Repository.

# Additional context:

##Are you contributing under any Open-source programme?

No

- [X] I am contributing under `GSSOC'24 Extended`
- [X] I am contributing under `Hacktoberfest'24`

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@Arveti-likhitha this pr is facing some merge conflicts please try to resolve this so that I can review & merge this pr
ASAP

**Comment by Arveti-likhitha** [comment]
@apu52 I have made changes. Can you check and let me know if there are any conflicts?

**Comment by apu52** [comment]
@Arveti-likhitha the conflicts are still present in this repo , please try to resolve them asap

**Comment by Arveti-likhitha** [comment]
@apu52 I resolved all the conflicts except for one. There is a conflict with the part of the code which is not present in the "index.html" file. So I am not able to resolve the conflict.

Could you guide me on how to resolve this?

**Comment by apu52** [comment]
@Arveti-likhitha u can do one thing , try to close this PR for now , 
Try to make a new branch on your forked repo & then make all of your proposed changes in that branch & try to push all of your commits in that branch & make/submit a new pr.

**Pull request closed without merging**
