### PR TITLE
feat: LOGIN PAGE IS UPDATED

### PR DESCRIPTION
**Pull request by AbheetHacker4278**
# Title and Issue number 
#900 

Title :
LOGIN PAGE IMPROVEMNT

Issue No. : #900 

Code Stack : HTML , CSS , JS

# Description
I have Updated the Login page with cool animated Background of Nature Theme.

# Video/Screenshots (mandatory)
**BEFORE**

Screenshot 2024-06-24 134930

**AFTER**

https://github.com/apu52/Travel_Website/assets/114290748/fd0ac52d-57f0-4018-b559-252eb6cb96a4

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

# Additional context:
EYES APPELING

##Are you contributing under any Open-source programme?

- [X] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by AbheetHacker4278** [comment]
@itsekta @apu52 please REVIEW THIS PR AND MERGE THIS PR WITH MAIN BRANCH.
Thank You

**Comment by AbheetHacker4278** [comment]
@itsekta @apu52 have you liked the changes

**Comment by itsekta** [comment]
Hey @AbheetHacker4278, nice try with the UI for the login page! Do you have any other options? Currently, I think the previous login UI looks better. The current design lacks consistency with padding, colors, and buttons.

**Comment by AbheetHacker4278** [comment]
> Hey @AbheetHacker4278, nice try with the UI for the login page! Do you have any other options? Currently, I think the previous login UI looks better. The current design lacks consistency with padding, colors, and buttons.

Okay I Understand , thanks for Honest Review , i think trip gallery sections need some update and changes , so i can add cool animated cards , is it Okay ?

**Comment by itsekta** [comment]
Yeah, go ahead you can work on it in a separate issue, I'm closing this for now.

**Pull request closed without merging**
