### PR TITLE
feat: NavBar added to all pages

### LINKED ISSUE #1258: [Feature Request]: Add new navbar to all pages
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

new Navbar should be added to all pages

### Use Case

better UI

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by sau-mili**
# Title and Issue number 

Title : Same Navbar added to All pages

Issue No. : #1258 

Code Stack :  HTML, CSS, JS

Close #1258 

# Description

- Identified navbar bugs and fixed it
- Same navbar edits added to all pages
- Included CSS, HTML, JS edits

# Video/Screenshots (mandatory)

### faq page
image
### cultural exp page
image
### honeymoon page
image
### adventure page
image

### rate us page
image

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by sau-mili** [comment]
@apu52 please check

**Review by apu52 — CHANGES_REQUESTED** [review]
image

in the cultural exp , adventure & honeymoon pages the navbar is not showing up properly , please fix this issue , other than all of the changes are well made

**Comment by sau-mili** [comment]
I will update it by tomorrow

**Comment by sau-mili** [comment]
Please check now:
## ADVENTURE PAGE
image
## HONEYMOON PAGE
image
## CULTURAL EXP PAGE
image

**Review by apu52 — APPROVED** [review]
@sau-mili good work

**Pull request merged**
