### PR TITLE
feat: Created socialmedia.html

### LINKED ISSUE #937: [Documentation Update]: Social footer is not aligned
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Screenshot (43)
see here social platforms are not segregated they are  mixed up please assign me under gssoc

### Suggested Change

see here social platforms are not segregated they are  mixed up please assign me under gssoc

### Rationale

_No response_

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by adityasingh-0803**
Added socialmedia section

#937 
Title : Addition of social media handles

Issue No. :#937

Code Stack : 

Close #937

# Description
As i have added the file as socialmedia.html in which I have make sure to add neccessary links and no misalignment is there 

# Video/Screenshots (mandatory)
Screenshot 2024-07-07 160631

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [X] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [ ] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?
Yes

- [X] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by adityasingh-0803** [comment]
KIndly review it and assign the necessary taggings to fetch points thanks @apu52

**Review by apu52 — CHANGES_REQUESTED** [review]
@adityasingh-0803 there is no code changes in this PR . what can I review???
there is only a new file u have created & I think your issue is to solve the misalignment problem of social icons in the footer

**Comment by adityasingh-0803** [comment]
Sir the file of this issue wasn't there so I created a new file

**Comment by apu52** [comment]
> Sir the file of this issue wasn't there so I created a new file

but in this file there is no code present there .can u please explain otherwise I can't be able to understand your PR

**Pull request closed without merging**
