### PR TITLE
fix: About US page is redirected to Home page

### LINKED ISSUE #1561: [Bug]: About US page is not redirecting
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Screenshot (483)
image

In About US page, after clicking the button there is no redirection to the home page.
image
I would like to work on this issue.

### Expected behavior

After fixing it the 404 error will be removed.

### Add ScreenShots/Videos

_No response_

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Zubaida0113**
# Title and Issue number 

Title : About US page is not redirecting

Issue No. : #1561

Code Stack : HTML

Close #1561 

# Description

Fix the redirection link from About Us page to the Home page and the Start journey buttons now redirected to Login page.
# Video/Screenshots (mandatory)

https://github.com/user-attachments/assets/c2a6e59d-20f9-4a7b-80e3-f68388332de2

# Type of PR

- [X] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing
- [X] I have Starred the Repository.

# Additional context:

##Are you contributing under any Open-source programme?

- [X] I am contributing under `GSSOC'24 Extended`
- [X] I am contributing under `Hacktoberfest'24`

### CODE REVIEW

**Comment by Zubaida0113** [comment]
@apu52 I have checked and updated my branch with the main branch, and the images are loaded properly. Can you list the steps by which you had the issue?

The image code is working fine.
image

There are other issues like the hamburger variable but it doesn't affect the images.
image

This is the video on my changes.
https://github.com/user-attachments/assets/5b4e674b-8d8b-47cb-bf79-a32ceb722d8b

https://github.com/user-attachments/assets/bc576a8a-e5c8-4adf-8703-78faf2480f88

**Comment by apu52** [comment]
> https://deploy-preview-1607--taupe-cendol-f7e2bb.netlify.app

This is the deployed link of your PR , like this Deployment will reflect that how your commits will show in the main web site as the final product . & I have also checked the deployment after your comment its still remains the same  , U can also check through this link

**Comment by Zubaida0113** [comment]
image
 This is showing from my side.
How about opening it in incognito mode, if it works then maybe there is cache issue in the browser.
OR
Should I delete this pull and push the branch again.
Let me know.

**Comment by apu52** [comment]
@Zubaida0113 try to make a new PR by updating your branch

**Review by apu52 — APPROVED** [review]
@Zubaida0113 okk now this link is working well , maybe there was some glitch ....

**Pull request merged**
