### PR TITLE
feat: Re-Created Cursor Trail Effect to The Website Across All Pages

### LINKED ISSUE #1014: Re-Create Cursor Trail Effect to The Website
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @apu52 

I would like to Re-create add a Cursor trail effect matching to the website design theme across all the pages of the website (for consistency)

The current one is not working properly nor it is sync to the cursor

**I will make sure:**

- It is smooth without lag.
- Aesthetically pleasing
- The trail effect does not interfere with other interactive elements on the page.
- It does not irritate to users instead it will be fun to play with!

### Expected behavior

It should work properly 

### Add ScreenShots

**Some examples of my works are:**

https://github.com/Indie-Kart/ecommerce-store/assets/101971980/9d9e741e-065e-4f65-893a-9a01b8ecba54

https://github.com/Indie-Kart/ecommerce-store/assets/101971980/2ec1964f-6ce8-4029-86f7-62d5df520211

https://github.com/Its-Aman-Yadav/Community-Site/assets/101971980/95dd3a00-a331-4cf3-ae8b-28319878190d

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MastanSayyad**
- Issue closes #1014

# Description

Hey @apu52 and @itsekta 

I have recreated and added the cursor trail effect across all the pages of the website

# Video/Screenshots (mandatory)

https://github.com/apu52/Travel_Website/assets/101971980/278bdc3f-fa6a-4a7c-8457-6585e88a859e

# Type of PR

- [x] Feature enhancement

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24`

### CODE REVIEW

**Comment by itsekta** [comment]
Hey @MastanSayyad, I liked the new cursor trails nice work. Let just wait for the Project admins response.

**Comment by MastanSayyad** [comment]
> Hey @MastanSayyad, I liked the new cursor trails nice work. Let just wait for the Project admins response.

Yeah okay, but pls reopen the issue so that the project admin don't get confused while merging

**Comment by itsekta** [comment]
He will not be confused. we have discussed it. But for your case i have opened it.

**Comment by MastanSayyad** [comment]
@apu52 Please merge this PR

**Review by apu52 — APPROVED** [review]
@MastanSayyad great work

**Pull request merged**
