### PR TITLE
feat: Enhance License and Acknowledgments Section and Project mentor section

### LINKED ISSUE #1095: Enhance License and Acknowledgments Section Clarity
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Without clear licensing information, users may hesitate to engage with or contribute to the project due to uncertainty about usage rights. Inadequate acknowledgment of contributors diminishes morale and recognition within the community.

### Suggested Change

Without clear licensing information, users may hesitate to engage with or contribute to the project due to uncertainty about usage rights. Inadequate acknowledgment of contributors diminishes morale and recognition within the community. Add a heartfelt message of gratitude to encourage further p
articipation and collaboration.

Assign this issue to me as a GSSOC 24 contributor

### Rationale

_No response_

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Zoha-Waheed**
# Title and Issue number 
Title : Enhance License and Acknowledgments Section Clarity

Issue No. : #1095

Code Stack : HTML, CSS, JS

Close #1095

# Description
# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [X] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

# Additional context:
##Are you contributing under any Open-source programme?

- [X] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@Zoha-Waheed can u provide here the SS of the enhanced readme after your changes??? So that I can get a clear idea

**Comment by Zoha-Waheed** [comment]
> @Zoha-Waheed can u provide here the SS of the enhanced readme after your changes??? So that I can get a clear idea

yes sure, I am attaching them below
image
image
image
image

**Comment by apu52** [comment]
@Zoha-Waheed all of the changes u have made are really good , but just want one thing there is a contributor slider now I the readme just add it in the acknowledgement section (above the contributor list) so that I will merge this pR.

**Comment by Zoha-Waheed** [comment]
> @Zoha-Waheed all of the changes u have made are really good , but just want one thing there is a contributor slider present now in the readme , just add it in the acknowledgement section (above the contributor list) so that I will merge this pR.

Thanks
Just check is it so?
image

**Comment by apu52** [comment]
> > @Zoha-Waheed all of the changes u have made are really good , but just want one thing there is a contributor slider present now in the readme , just add it in the acknowledgement section (above the contributor list) so that I will merge this pR.
> 
> Thanks Just check is it so? image

yess .Now push this changes in this PR & ping me here after that , then I will merge this PR.

**Comment by Zoha-Waheed** [comment]
> > > @Zoha-Waheed all of the changes u have made are really good , but just want one thing there is a contributor slider present now in the readme , just add it in the acknowledgement section (above the contributor list) so that I will merge this pR.
> > 
> > 
> > Thanks Just check is it so? image
> 
> yess .Now push this changes in this PR & ping me here after that , then I will merge this PR.

Changes are already committed in this PR. Anything else, then sure.

**Review by apu52 — APPROVED** [review]

**Comment by apu52** [comment]
@Zoha-Waheed Thanks for your valuable contribution.

**Pull request merged**
