### PR TITLE
feat: Enhancing About Section

### LINKED ISSUE #1084: Enhancing About Section
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Would like to add a background to ABOUT section as it seems simple compared to rest of the website.

### Use Case

This would enhance the look of the  website making it visually appealing to the viewers.

### Benefits

_No response_

### Add ScreenShots

Screenshot 2024-07-15 233604

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by AshmitaBarthwal**
# Title and Issue number 

Title: Enhancing About Section 

Issue No. : #1084

Code Stack : CSS

Close #1084

# Description

Made Changes to the ABOUT section of the website so as to make it more attractive.

# Video/Screenshots (mandatory)

Screenshot (273)

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [X] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by itsekta** [comment]
Hey @AshmitaBarthwal, the sections looks good. Your PR will be merged soon.

**Comment by AshmitaBarthwal** [comment]
@itsekta thankyou. Could you mark my LEVEL of contirbution label to it ??

**Review by apu52 — APPROVED** [review]
@AshmitaBarthwal all the changes u have made are well changes

**Review by apu52 — CHANGES_REQUESTED** [review]
image

But I can see there is a bug that the dark theme is not working in the home page . S please try to fix that so that I can merge the PR

**Comment by AshmitaBarthwal** [comment]
@apu52 I made the necessary changes. Shall I create a new pull request for this ???

**Comment by AshmitaBarthwal** [comment]
Screenshot 2024-07-17 145256

**Comment by AshmitaBarthwal** [comment]
@apu52 MARK THE LEVEL OF CONTRIBUTION LABEL UNDER GSSOC

**Comment by AshmitaBarthwal** [comment]
@apu52 Please review my Pull Request.

**Comment by AshmitaBarthwal** [comment]
@itsekta Please review my updated Pull Request.

**Comment by apu52** [comment]
> Screenshot 2024-07-17 145256

it is not the authentic color of the text font of the website in the dark mode .please change it to the custom . U can get the color codes from the original repo .please check that

**Comment by AshmitaBarthwal** [comment]
I Have made the necessary changes And i am creating a new pull request to void any confusion @apu52

**Comment by itsekta** [comment]
Hey @AshmitaBarthwal, please create a new PR. I'm closing this one because it includes changes to the Google logo CSS and other elements. Please address one issue at a time. For the About Us section, ensure that the color combination matches the current UI, as the colors you used are not suitable.

**Comment by AshmitaBarthwal** [comment]
@itsekta YES I have created a new pull request.

**Pull request closed without merging**
