### PR TITLE
fix: Position of Night mode button

### PR DESCRIPTION
**Pull request by manikdamle**
# Title and Issue number 

Title  :Night mode button was not clearly visible in the navbar

Issue No. : #1430

Code Stack : 

Close #<#1430>

# Description

Night mode button was not clearly visible in the navbar. It is now visible.

# Video/Screenshots (mandatory)

# Type of PR

- [X] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing
- [x] I have Starred the Repository.

# Additional context:

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24 Extended`
- [x] I am contributing under `Hacktoberfest'24`

### CODE REVIEW

**Comment by manikdamle** [comment]
@apu52 Pls review

**Comment by manikdamle** [comment]
Hey @apu52 , can you pls review and merge if everything is ok?

**Review by apu52 — CHANGES_REQUESTED** [review]
@manikdamle this pr is facing some merge conflicts please try to resolve this so that I can review & merge this pr

**Comment by manikdamle** [comment]
@apu52 resolved them. Pls check

**Review by apu52 — CHANGES_REQUESTED** [review]
https://github.com/user-attachments/assets/9680ac5a-fb12-4d9f-b4f6-b58d5711550a

the changes u have made due to that the hamburger icon in the small width screen of the website does not working due to overlapping with the theme toggle .please try to fix that

**Pull request closed without merging**
