### PR TITLE
fixed date issue

### PR DESCRIPTION
**Pull request by Pranjalidhale0711**
### Changes Implemented

Date Validation: Added JavaScript validation to ensure the end date cannot be earlier than the start date.
Alert Message: Displays an alert if the end date is earlier than the start date, preventing form submission.
Form Submission: The form's submit event is intercepted to perform the date check before proceeding.

### Purpose
This change ensures that users cannot select an end date that is before the start date, which would be logically incorrect for planning a trip.

### Details
JavaScript Function:

Created a handleSubmit function that performs the date comparison.
If the end date is earlier than the start date, an alert is shown to the user and the form submission is prevented.
If the dates are valid, the form can be submitted successfully.
Event Listener:

Added an event listener to the form's submit event to call the handleSubmit function.

[
Screenshot 2024-05-21 at 9 15 01 PM

### CODE REVIEW

**Comment by apu52** [comment]
@Pranjalidhale0711 have you raised an issue before making the PR ???
As no issue is mentioned in the PR

**Comment by Pranjalidhale0711** [comment]
Yes sir I have raised an issue before PR.


Following is the issue
End Date Can Be Set Earlier Than Start Date #523

**Review by apu52 — COMMENTED** [review]
@Pranjalidhale0711 Please don't make any type of PR until & unless you get assigned to any issue .I am closing this PR as unplanned . Now I have assigned you . Now you can submit your PR

**Comment by apu52** [comment]
@Pranjalidhale0711 & also please follow the proper PR template next time

**Comment by Pranjalidhale0711** [comment]
Ok sir

**Pull request closed without merging**
