### PR TITLE
feat: Added Popular Categories with full logic

### LINKED ISSUE #1251: [Feature Request]: Making the quicklinks and categories functionable
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

image
Want to make them functionable

### Use Case

image
Want to make them functionable

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by ayush-848**
# Title and Issue number 
Title : Added Popular Categories with full logic

Issue No. : #1251

Code Stack : js

Close #1251

# Description
- **Display Top 5 Categories**: Ranks and shows the top 5 categories based on their frequency.
- **Category Filtering**: Clicking on a category filters blog posts to only show those with the selected category.
- **Dynamic Category List**: Updates the category list dynamically based on the blog posts data.

# Video/Screenshots (mandatory)
https://www.awesomescreenshot.com/video/29994250?key=219b315397adef7a03fc3ab374a86f8a

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by ayush-848** [comment]
@apu52 
image
I have also added relevant link in the quicklinks that are totally functional

**Comment by ayush-848** [comment]
@apu52 Can I get a level 3 for this????

**Comment by ayush-848** [comment]
@apu52 please check this

**Comment by apu52** [comment]
> @apu52 Can I get a level 3 for this????

I can max assign u level 2 for this PR

**Review by apu52 — APPROVED** [review]
@ayush-848 good work

**Pull request merged**
