### PR TITLE
Added the component in Navbar

### LINKED ISSUE #117: Feature_Request: Addition of  "About Us" in navigation bar
**Is your feature request related to a problem? Please describe.**

we can add an information block of  website in navigation bar.

**Demo Video/Screenshot (Mandatory )**
Screenshot 2024-01-21 095357

***Are you contributing under any open-source program ?***

Yes Under JWOC 2024

### PR DESCRIPTION
**Pull request by shreya9x1**
# Title and Issue number 

Title :

Issue No. :#117

Code Stack : 

Close #117 

# Video/Screenshots (mandatory)

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

Yes JWOC 2024

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@shreya9x1 There is merge conflicts & the PR template is not properly filled .

**Comment by apu52** [comment]
& also the about us section is not visible in the dark theme . make the changes in CSS

image

**Review by apu52 — CHANGES_REQUESTED** [review]
@shreya9x1 Have you resolved the conflicts . as I can see there is a bug in the  changes you have made , like 
image

Please remove the above portion  of **"EXPLORE TOP DESTINATION"** in the webpage

**Comment by shreya9x1** [comment]
> @shreya9x1 There is merge conflicts & the PR template is not properly filled .

Respected Sir, I'm facing a problem in this as the updates made by regarding dark screen mode is not visible in my forked repository. Kindly help me out with this So that I can make the changes of dark mode in "About Us" block.

**Comment by shreya9x1** [comment]
> & also the about us section is not visible in the dark theme . make the changes in CSS
> 
> image

Respected Sir, I'm facing a problem in this as the updates made by regarding dark screen mode is not visible in my forked repository. Kindly help me out with this So that I can make the changes of dark mode in "About Us" block.

**Comment by apu52** [comment]
> > & also the about us section is not visible in the dark theme . make the changes in CSS
> > image
> 
> Respected Sir, I'm facing a problem in this as the updates made by regarding dark screen mode is not visible in my forked repository. Kindly help me out with this So that I can make the changes of dark mode in "About Us" block.

@shreya9x1 I want to suggest you to update your branch to your Forked repo by clicking on the "SYNC FORK" option. So that In  that branch you can make your changes & make a PR . 

image

**Comment by apu52** [comment]
@shreya9x1 I want to suggest you to make a new PR making a new updated branch in your forked repo & make changes there. I am closing this PR . Please submit your new PR . If you need any more help you can reach out to me in Discord

**Pull request closed without merging**
