### PR TITLE
fix: Nav-bar in story page

### LINKED ISSUE #1147: [Bug]:  Old nav-bar in story.html
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The nav bar in the story page is old. Its logo as well as the format is old.

### Expected behavior

Clicking on the circular button in the homepage (index.html) will hyperlink us to the story page (story.html)
image

### Add ScreenShots

Story Page:
image

Home Page:
image

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by VijaySamant4368**
# Title and Issue number 

Title :  Nav-bar in story page fixed

Issue No. : #1147 

Close #1147

# Description

The navigation bar in the story page(story.html) was old version, I updated it to be the latest one.

# Video/Screenshots (mandatory)

image

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by VijaySamant4368** [comment]
@itsekta @apu52 please kindly check this out.

**Comment by VijaySamant4368** [comment]
@itsekta @apu52 please kindly check this out.

**Review by apu52 — CHANGES_REQUESTED** [review]
@VijaySamant4368 there is some recent changes in the story page .please try to resolve the conflicts so that I can review the PR & will be able to merge the PR

**Comment by VijaySamant4368** [comment]
@apu52 I resolved the conflicts.

**Comment by VijaySamant4368** [comment]
Can I get a level 2 label?

**Comment by apu52** [comment]
@VijaySamant4368 after the changes u have made in the navbar of the story page the navbar is not working at all. The navbar is just static . please try to resolve it

**Comment by VijaySamant4368** [comment]
I am sorry for the incontinence, I will immediately look into it.

**Comment by VijaySamant4368** [comment]
@apu52 I think the problem is that the hyperlinks are wrong, I will fix it in just a moment.

**Comment by VijaySamant4368** [comment]
The error is not solved in this last merge

**Comment by VijaySamant4368** [comment]
@apu52 I have corrected the nav-links

**Comment by apu52** [comment]
@VijaySamant4368 I have checked twice , also have refreshed , but the problem is still there....u can also check in the deployed link also

**Review by apu52 — APPROVED** [review]
@VijaySamant4368 okk Now , it's working

**Pull request merged**
