### PR TITLE
Added Navbar with edition of styling in Dark Mode

### PR DESCRIPTION
**Pull request by shreya9x1**
# Title and Issue number 

Title : recreated a branch to edit the about us section in dark mode

Issue No. :#117

Close : #117

Code Stack : Screenshot 2024-01-23 215103

Close #<117> 

# Video/Screenshots (mandatory)

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***
 Yes Under JWOC'24

### CODE REVIEW

**Comment by shreya9x1** [comment]
Sir,Kindly check Once!

**Comment by apu52** [comment]
@shreya9x1 The about section is really good . but there is some changes in the login page in your PR. Just make the alignment changes in the login pg so that I can merge the PR

image

Make the login pg in the center & also remove the home button

**Review by apu52 — CHANGES_REQUESTED** [review]
look at the comment

**Comment by shreya9x1** [comment]
Sir I changed login page and have pulled another request kindly check

**Comment by apu52** [comment]
> Sir I changed login page and have pulled another request kindly check

@shreya9x1 This PR have merge conflicts & also don't make multiple PR on a single issue. make all the changes in the SAME PR. I am closing the other PR . Make the changes in the same PR

**Comment by shreya9x1** [comment]
Sir, I have made the changes in Login page, kindly check

**Comment by apu52** [comment]
image

Still having this problem. I would like to suggest you to close this PR &make a new branch & make all the changes there @shreya9x1

**Comment by shreya9x1** [comment]
Ok sir close this one

**Pull request closed without merging**
