### PR TITLE
feat: Updated navbar colors and fixed alignment issues

### LINKED ISSUE #1063: Enhancement: Improve Styling for Thank You Page, Navbar, and Trending Tour Card Alignment.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I am proposing enhancements to improve the visual appeal and user experience of the travel website:

### Suggested Change

hank You Page:

Update the styling to make it more eye-catching and visually appealing. Changes will include:
Enhancing the color scheme.
Improving layout and typography.

Thank You Page:

Update the styling to make it more eye-catching and visually appealing. Changes will include:
Enhancing the color scheme.
Improving layout and typography.

Trending Tour Card Alignment:

Currently, the alignment of the trending tour cards appears unorganized.
Plan to adjust alignment and layout for a more structured and visually appealing presentation.

Here's a draft for your GitHub issue based on the changes you made:

Title: Enhancement: Improved Styling for Thank You Page, Navbar, and Trending Tour Card Alignment

Description:

I have implemented several enhancements to improve the visual appeal and user experience of the travel website:

Thank You Page:

Updated the styling to make it more eye-catching and visually appealing. The changes include:
Enhanced color scheme.
Improved layout and typography.
Navbar:

Changed the navbar color to a lighter shade to improve visibility and aesthetics.
Adjusted the hover color to match the new color scheme for better user experience.
Trending Tour Card Alignment:

Found the trending tour cards to be unorganized.
Adjusted the alignment and layout for a more structured and visually appealing presentation.
Here are some screenshots of the changes:

Thank You Page:

Navbar:

Trending Tour Cards:

I worked on these enhancements without raising an issue initially. I am now raising this issue to align with the contribution guidelines. Please review and assign it to me.

Thank you!
Thank You Page:
Screenshot (1988)
Navbar:
Screenshot (1989)

Screenshot (1990)
Screenshot (1991)
Trending card:
Screenshot (1986)
Screenshot (1987)

### Rationale

I've dedicated significant effort, approximately six hours, to enhancing the styling of key web pages within the travel website. While these changes may seem small in scope, they contribute significantly to improving the user experience and visual appeal of the platform. This effort underscores my commitment to making meaningful contributions to the project.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by PRANJALIMALETHA**
Title: Enhancement: Improved Styling for Thank You Page, Navbar, and Trending Tour Card Alignment

Issue No.: #1063

Code Stack: HTML, CSS, JavaScript

Close #1063

# Description
Enhanced the visual appeal and user experience of the travel website by updating the styling for the Thank You Page, Navbar, and Trending Tour Card alignment. Details include:

- Updated Thank You Page with enhanced color scheme and typography .
- # Description
Enhanced the visual appeal and user experience of the travel website's Thank You Page by implementing the following stylistic improvements:

- **Color Scheme Enhancement**: Updated the color scheme to incorporate soothing tones that align with the travel theme, enhancing visual coherence and brand identity.
  
- **Typography Improvement**: Refined typography choices for improved readability and aesthetic appeal, ensuring a harmonious blend with the overall design.

- **Box Shadow Application**: Applied subtle box shadows to elements within the Thank You Page, adding depth and a sense of dimensionality to key components.

- **Linear Gradient Usage**: Integrated subtle linear gradients to create a smooth transition between colors, enhancing visual interest without overpowering the content.

- **Text Shadow Utilization**: Implemented delicate text shadows to enhance legibility and visual prominence of important text elements, improving overall readability under varying lighting conditions.

These enhancements collectively aim to create a more engaging and visually appealing Thank You Page experience for users, aligning with modern design trends while maintaining usability and accessibility standards.

- Optimized Navbar for better visibility and user experience.
### Navbar:
- **Color Adjustment**: Changed the navbar color to `lightblue` for a more vibrant and user-friendly appearance.
- Adjusted the downward portion color to `light blue` to create a lighter contrast with the background, improving overall visibility and reducing visual intensity.

- Improved alignment and layout of Trending Tour Cards for a more structured presentation.
##- **Hover Effects**: Implemented hover effects to highlight the cards on interaction, improving user engagement.
- **Layout Adjustment**: Arranged the Trending Tour Cards to ensure proper alignment and spacing, addressing previous issues of disorganization.
- **Button Positioning**: Corrected the positioning of buttons within the cards by adjusting the margins from the left and right sides, ensuring they are properly aligned and visually appealing.

# Video/Screenshots (mandatory)

Screenshots:
- Screenshot of Thank You Page](https://github.com/user-attachments/assets/6488e486-b472-4b5d-a380-787bc21a2968)

- Screenshot of Navbar
Screenshot (1989)
Screenshot (1990)
Screenshot (1991)

- Screenshot of Trending Tour Cards
Screenshot (1986)
Screenshot (1987)

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have gone through the `contributing.md` file before contributing

# Additional context:

## Are you contributing under any Open-source programme?
I am contributing under `GSSOC'24`. My goal is to enhance the user experience of the travel website through these improvements.

- [x] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by PRANJALIMALETHA** [comment]
is my pr is successful

**Comment by PRANJALIMALETHA** [comment]
Is my pr request is successful

**Comment by PRANJALIMALETHA** [comment]
Enhanced the styling of the Thank You Page, Navbar, and Trending Tour Cards to improve visual appeal and user experience. Changes include color scheme updates, typography refinements, and layout adjustments. Screenshots attached for reference.

**Comment by apu52** [comment]
> Is my pr request is successful

yes it's successful .I am reviewing it

**Review by apu52 — APPROVED** [review]
@PRANJALIMALETHA good work

**Pull request merged**
