### PR TITLE
fix: Repetitive tagline issue #752

### LINKED ISSUE #752: Repetitive tagline in destination, trip package, and gallery sections
**Describe the bug**
The line "Explore your suitable and dream places around the world. Here you can find your right destination." is repeated in the destination, trip package, and gallery sections. This repetition affects the uniqueness and professionalism of the website.

**Expected behavior**
Each section should have a unique and relevant tagline that enhances the user experience and provides clear, distinct information about each section.

**Screenshots (Mandatory)**
image
image

***Are you contributing under any open-source program ?***
GSSoC'24

### PR DESCRIPTION
**Pull request by TBorundia**
# Title and Issue number 
Title : Repetitive tagline in destination, trip package, and gallery sections, etc.

Issue No. : #752

Code Stack : 

Close #752

# Description
Updated taglines for the sections of the travel website to ensure each one is unique and inspiring.

# Video/Screenshots (mandatory)
image
image
image
image
image

# Type of PR
- [X] Feature enhancement

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

# Additional context:
Updated repetitive taglines with unique and inspiring ones to enhance user engagement and clarity.

##Are you contributing under any Open-source programme?
GSSoC'24

### CODE REVIEW

**Comment by TBorundia** [comment]
@apu52 Sir I have completed the task. Can you please check it?

**Review by apu52 — APPROVED** [review]
@TBorundia good work

**Comment by TBorundia** [comment]
> @TBorundia good work

Sir I will not get level 2 for it as I have changes 5 tag lines and improved the CSS to give proper spaceing and adjustment to lines?

**Comment by apu52** [comment]
> > @TBorundia good work
> 
> Sir I will not get level 2 for it as I have changes 5 tag lines and improved the CSS to give proper spaceing and adjustment to lines?



> > @TBorundia good work
> 
> Sir I will not get level 2 for it as I have changes 5 tag lines and improved the CSS to give proper spaceing and adjustment to lines?

Sorry @TBorundia as per my review I can assign u level1 only , but don't worry keep up your contributions.

**Pull request merged**
