### PR TITLE
feat: Added a Back-To Home Button on The Login Page 

### PR DESCRIPTION
**Pull request by RadhikaMalpani1702**
# Title and Issue number 

Issue fixes : #1018

# Description

Hey @itsekta and @apu52 

I have added a Back-To-Home Button on The Login Page.

# Video/Screenshots (mandatory)

image

# Type of PR

- [X] Feature enhancement

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [X] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by itsekta** [comment]
Hey @RadhikaMalpani1702, the position for the home icon is not good, Try adding a left arrow in a circle instead of home icon on the left side of the title **Tour Guide** with some proper padding and all, it will look more great there 

Screenshot 2024-07-09 071356

**Comment by RadhikaMalpani1702** [comment]
Hey @itsekta 

I am unable to change the position because it is breaking the login page 
Is this okay?

image

**Comment by itsekta** [comment]
Hey @RadhikaMalpani1702, for a good UI the position is not best for the arrow, what are the breaking changes as i have tried the same and it's working. Try one more time, If you are still facing any issue let connect over discord just ping me there.

**Comment by itsekta** [comment]
@RadhikaMalpani1702 are you still working on this?

**Comment by RadhikaMalpani1702** [comment]
@itsekta Yes I am

**Comment by RadhikaMalpani1702** [comment]
@itsekta and @apu52 Changes are done please merge this PR

**Review by apu52 — APPROVED** [review]
@RadhikaMalpani1702 I have reviewed it  & as per the changes @itsekta has suggested its working well . I have approved this

**Comment by apu52** [comment]
now , ma'am @itsekta I request u to  please review this PR also so that I can merge it under GSSOC'24

**Comment by RadhikaMalpani1702** [comment]
@itsekta Please review it.

**Comment by RadhikaMalpani1702** [comment]
@apu52 If you have already reviewed it then please merge it

**Comment by apu52** [comment]
@RadhikaMalpani1702 I have merged it

**Pull request merged**
