### PR TITLE
payment page

### LINKED ISSUE #80: Feature_Request : Checkout page for tour packages
**Is your feature request related to a problem? Please describe.**

the book now button of the destination card are not linked to any checkout page.

**Describe the solution you'd like**

I would like to build a dummy checkout page (non functional, as of now), which will be linked to the book now button.

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
inspiration
Screenshot 2024-01-18 150145

***Are you contributing under any open-source program ?***

JWoC'24

### PR DESCRIPTION
**Pull request by PranavBarthwal**
# Title and Issue number 

Title : payment page

Issue No. : #80

Code Stack : html css bootstrap

Close #80

# Video/Screenshots (mandatory)

Screenshot 2024-01-23 012937
Screenshot 2024-01-23 013504

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**
also added a breadcrumb on the top left

***Are you contributing under any Open-source programme?***

JWOC'24

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@PranavBarthwal This is a very good contribution But how we can deploy to the checkout page from the HOME page as there is no button . I want to suggest you to make the checkout page from clicking  **"Book now"** button
link the payment.html page with the main HTML page

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal This is a very good contribution But how we can deploy to the checkout page from the HOME page as there is no button . I want to suggest you to make the checkout page from clicking **"Book now"** button link the payment.html page with the main HTML page

okay. linking book now button in hero section, and all the tour packages to the payment page.

**Comment by PranavBarthwal** [comment]
@apu52 Done. linked the payment page with every book now button on packages page, and on hero section

**Review by apu52 — APPROVED** [review]
great work

**Pull request merged**
