### PR TITLE
fix: Footer of Trip Package page fixed

### PR DESCRIPTION
**Pull request by TBorundia**
# Title and Issue number 
Title : Footer of Trip Package page fixed

Issue No. : #1105

Code Stack : 

# Description
1. Added Social media icons.
2. Added google translator.
3. Map for address location.
4. Alignment issue of text.
5. Responsive footer for all screen size.

# Video/Screenshots (mandatory)
Screenshot 2024-07-18 185021

Screenshot 2024-07-18 185058

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X]  I have performed a self-review of my code.
- [X]  I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

##Are you contributing under any Open-source programme?
- [X] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by TBorundia** [comment]
@apu52 @KrishnenduDG ,
Please review this PR. Thank You!

**Review by apu52 — CHANGES_REQUESTED** [review]
@TBorundia this PR has some merge conflicts .please try to resolve the conflicts so that I can review the codes & be able to merge the PR

**Comment by TBorundia** [comment]
> @TBorundia this PR has some merge conflicts .please try to resolve the conflicts so that I can review the codes & be able to merge the PR

@apu52 Sir, Please check it now.
I have resolved conflicts.

**Review by apu52 — CHANGES_REQUESTED** [review]
image

the trip package footer is really looking messy .please try to resolve it

**Comment by TBorundia** [comment]
@apu52 Sir, please check it now, I have made the changes.

image


image

**Comment by TBorundia** [comment]
@apu52 Sir, please check it now, I have made the changes.

image


image

**Comment by TBorundia** [comment]
@apu52 Sir, please check it now, I have made the changes.

image


image

**Review by apu52 — APPROVED** [review]
@TBorundia really great work. Really great that u have solved the conflicts

**Pull request merged**
