### PR TITLE
color changed from blue to white

### LINKED ISSUE #438: BUG: In footer
**Describe the bug**
In the footer, only the Support section is highlighted in blue, while all other items are displayed in white.

**Expected behavior**
The expected behavior is for the Support section to also be displayed in white.

**Screenshots (Mandatory)**
image

Expected
image

**Additional Context (Mandatory )**
The expected behavior is for the Support section to also be displayed in white, enhancing user experience and readability

***Are you contributing under any open-source program ?***
gssoc 2024

### PR DESCRIPTION
**Pull request by abhayvershwal**
issue: #438 

Close #438

# Video/Screenshots (mandatory)
image

**Additional context (Mandatory )**
I have updated the footer color from blue to white, which now appears more consistent and improves readability.

***Are you contributing under any Open-source programme?***
gssoc 2024

### CODE REVIEW

**Comment by abhayvershwal** [comment]
@apu52  kindely check my PR

**Review by apu52 — APPROVED** [review]
Good work @abhayvershwal

**Comment by abhayvershwal** [comment]
@apu52  I have thoroughly reviewed the code in the testimonial section and found no issues. Accordingly, please approve and merge my pull request. Additionally, assign me to the second issue, #472. Thank you.

**Comment by abhayvershwal** [comment]
@apu52 and if you want me to make PR on some other branch then i can change that from main to updated or new

**Comment by apu52** [comment]
> @apu52 and if you want me to make PR on some other branch then i can change that from main to updated or new

yes. I will always suggest that to make all of your changes in new branch(in the forked repo) instead of the MAIN branch & make a new PR . So I am closing this PR , just make a new PR on a new branch & submit it

**Comment by apu52** [comment]
> @apu52 I have thoroughly reviewed the code in the testimonial section and found no issues. Accordingly, please approve and merge my pull request. Additionally, assign me to the second issue, #472. Thank you.

mentors will soon took review all of your issues

**Pull request closed without merging**
