### PR TITLE
solved the copyrightBUG_index.html

### LINKED ISSUE #337: BUG in copyright
**Describe the bug**
 copyright is displaying website created year not the current year , i.e it is showing 2023 rather than 2024 

**Expected behavior**
It will display current year i.e 2024 till 31st dec 2024 , and in 2025 it will automatically display 2025

***Are you contributing under any open-source program ?***
I am contributing under gssoc24

@apu52 Please assign this issue to me I will fix it .

### PR DESCRIPTION
**Pull request by Meetjain1**
I Have solved the copyright bug using javascript, now it will display current year. Thankyou

# Title and Issue number 

Title :  BUG in copyright

Issue No. : #337 

Code Stack : Html, Javascript

Close #337 >

# Screenshots :
Attached

copyright

# Checklist:

* [X] I have mentioned the issue number in my Pull Request.
* [X] I have commented my code, particularly in hard-to-understand areas
* [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**
I love to contribute in this project. Thankyou

***Are you contributing under any Open-source programme?***
Yes, Under Gssoc24.

### CODE REVIEW

**Comment by Meetjain1** [comment]
@apu52 any issue in this PR sir please let me know , This pr is for the issue #337 . Thankyou

**Comment by Meetjain1** [comment]
@apu52 Sir I request you to please have a look on this pr and merge it , If there is any issue please let me know , Thankyou .

**Comment by Meetjain1** [comment]
@Ghanshyam89 sir have a look on this PR .

**Review by apu52 — APPROVED** [review]
@Meetjain1 good work

**Comment by Meetjain1** [comment]
> @Meetjain1 good work

@apu52 Thanks a lot sir

**Comment by apu52** [comment]
> > @Meetjain1 good work
> 
> @apu52 Thanks a lot sir

@Meetjain1 Please don't call me sir .I am just a student

**Comment by Meetjain1** [comment]
> > > @Meetjain1 good work
> > 
> > 
> > @apu52 Thanks a lot sir
> 
> @Meetjain1 Please don't call me sir .I am just a student

Ok 😅

**Pull request merged**
