### PR TITLE
feat: UI of Hotel Booking Form and responsive

### LINKED ISSUE #1125: [Feature Request]:  UI of Hotel Booking Form to match website theme
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to request a new user interface design for the hotel booking form to enhance its usability and aesthetics. The current form lacks visual appeal and does not align with the overall theme of our website. An improved UI would make the form more intuitive and visually appealing to users.

### Use Case

This feature would enhance the user experience by making the hotel booking process smoother and more enjoyable. A well-designed form would reduce user frustration and increase conversion rates, as users would find it easier to complete their bookings.

### Benefits

_No response_

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by TBorundia**
Title : UI of Hotel Booking Form and responsive

Issue No. : #1125

Code Stack : 

Close #1125

# Description
Improved UI to match with website theme.
Added pop-up on submission of form.
Navigation button to home page.
Made the page responsive for all screen size.

# Video/Screenshots (mandatory)

https://github.com/user-attachments/assets/0a764a3b-b0aa-4b34-8509-b6c44d968076

https://github.com/user-attachments/assets/aa4a580d-02ef-43ec-8372-6224fdf6e08a

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X]  I have performed a self-review of my code.
- [X]  I have commented my code, particularly in hard-to-understand areas.
- [X]  I have tested the changes thoroughly before submitting this pull request.
- [X]  I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X]  I have gone through the  `contributing.md` file before contributing

##Are you contributing under any Open-source programme?
- [X]  I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by TBorundia** [comment]
@apu52 Sir,
Please review this PR. Thank You!

**Review by apu52 — APPROVED** [review]
@TBorundia really great work .thanks for your valuable contribution

**Comment by apu52** [comment]
> @apu52 Sir, Please review this PR. Thank You!

i have reviewed , it's really a great contribution. just one request , please don't call me sir , I am just a student

**Comment by TBorundia** [comment]
@apu52 ,
Thank you for the feedback. 
Ok, from next time I'll keep that in mind and won't use 'sir'.

**Pull request merged**
