### PR TITLE
Responsive contact us

### LINKED ISSUE #406: BUG
**Describe the bug**

The contact us page is not responsive.

**Expected behavior**

 Assign this task to me and I will make the page responsive.
**Screenshots (Mandatory)**

Screenshot (410)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***
Yes I am contributing under GGSOC'24

### PR DESCRIPTION
**Pull request by meetarora10**
# Title and Issue number 

Title :The contact us page is not responsive.

Issue No. :#406

Code Stack : CSS

Close #406

# Video/Screenshots (mandatory)

Screenshot (417)
Screenshot (415)

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***
Yes I am contributing under GGSOC'24

### CODE REVIEW

**Comment by meetarora10** [comment]
Hi @apu52 ,
Can you please take a moment and review this PR.

**Review by apu52 — CHANGES_REQUESTED** [review]
@meetarora10 There are merging conflicts in this PR . please try to resolve the issues so that I can review & merge the PR

**Comment by meetarora10** [comment]
@apu52 I have made the changes.

**Review by apu52 — APPROVED** [review]
@meetarora10 Good work

**Comment by meetarora10** [comment]
Thank you @apu52

**Pull request merged**
