### PR TITLE
Added Animations to make the website look Impressive.

### LINKED ISSUE #109: Feature_Request  Add Scrolling Animations to make the website Impressive .
**Is your feature request related to a problem? Please describe.**
Add Scrolling Animations to make the website Impressive  and much more Professional.

***Are you contributing under any open-source program ?***
Yes , I am contributing Under JWOC 2024. Please assign this issue to me under JWOC 2024.

### PR DESCRIPTION
**Pull request by SohanRC**
# Title and Issue number 

Title : Added Animations

Issue No. : 109

Code Stack : HTML , CSS , JS

Close #109 

# Video/Screenshots (mandatory)

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

YES , I am contributing in JWOC 2024.

### CODE REVIEW

**Comment by SohanRC** [comment]
@apu52  I have resolved the conflicts. Please review the PR again.

**Comment by apu52** [comment]
@SohanRC Please attach the demo video on which changes you have made to the website

**Comment by SohanRC** [comment]
Added Demo Video here.

https://github.com/apu52/Travel_Website/assets/124901633/fe823513-98b2-4114-8360-582622c2d4ae

**Comment by SohanRC** [comment]
@apu52  I have added the Video now. Please check

**Pull request closed without merging**
