### PR TITLE
fix: Improved navbar style on different pages and improved navigation/redi…

### LINKED ISSUE #1626: [Bug]: Navbar styling is not consistent across all pages
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The navbar styling is not consistent across all pages. The font size, colors, and alignment of the navbar vary depending on the page, which creates a disjointed user experience. Some pages show different spacing or background colors in the navbar, making it appear unpolished.

### Expected behavior

The navbar should have a uniform style across all pages, with consistent font size, colors, alignment, and spacing. Users should experience a seamless transition when navigating from one page to another without any changes in the navbar's appearance.

### Add ScreenShots/Videos

Screenshot 2024-11-05 005942
Screenshot 2024-11-05 010149

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by jitendrasuthar1998**
…rection flow

# Title and Issue number 

Title : Navbar styling is not consistent across all pages

Issue No. #1626 

Close #1626 

# Description

1. Made navbar style consistent on different pages
2. Improved navigation flow on different pages

# Video/Screenshots (mandatory)

# Type of PR

- [X] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have gone through the  `contributing.md` file before contributing
- [ ] I have Starred the Repository.

# Additional context:

##Are you contributing under any Open-source programme?

- [X] I am contributing under ` KWOC 2024`

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
image

All of the changes u have made are really good , but through the changes u have made this button is misaligned , please try to fix this as its original place , so try to fix it so that i can merge this pr

**Comment by jitendrasuthar1998** [comment]
@apu52 Ohk. I will align button and then update PR.

**Comment by jitendrasuthar1998** [comment]
@apu52 I have done the required changes.

image

**Review by apu52 — APPROVED** [review]
@jitendrasuthar1998 really great work , Thanks for your valuable contribution

**Pull request merged**
