### PR TITLE
Made the Website Responsive in Desktop Version.

### LINKED ISSUE #178: BUG : Make the Website responsive in Desktop version
**Describe the bug**

Hello All,
The webpage is not really responsive for all the Zoom portion in the webpage desktop version & also the color is not static in the background

**Expected behavior**

- I want to make the background in one static color or some animation design 
- & also make the website desktop responsive to all the zoom options
- & also make the background with some animation & maybe with some bgm music

**Screenshots (Mandatory)**

image
make the alignments ok

image
Make the background well like this . it's a demo.

**Additional Context (Mandatory )**

### Those whoever want to work on this issue comments first with JWOC mentioned on it I will assign it to HER/HIM

***Are you contributing under any open-source program ?***

JWOC'24

### PR DESCRIPTION
**Pull request by SohanRC**
# Title and Issue number 

Title : Made the Website Responsive in Desktop Version.

Issue No. : **#178** 

Code Stack :  HTML , CSS , JS

Close #178 

# Video/Screenshots (mandatory)

Made the website responsive under DESKTOP version and ADDED A ANIMATED BACKGROUND !!!
Screenshot 2024-01-28 130813

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

YES , under JWOC 2024.

### CODE REVIEW

**Comment by SohanRC** [comment]
@apu52  I have fixed the Responsiveness in Desktop version , added the Animated background as told in ISSUE NO = #178 . Please review and merge it . Also tell if some change is required !!!

**Comment by SohanRC** [comment]
@apu52 Please look into it and Also Suggest Some Changes which can be made if required now. The Last one I did not add the about us section. It was my fault ! Sorry for that ! But now i have added it. Please review it !

**Comment by SohanRC** [comment]
@apu52 Please check it !

**Comment by apu52** [comment]
@SohanRC the bg is okay . But try to enhance it. Like make it more appropiate .
This changes can't be merged right now. but I am giving you time of 2 days to submit your PR on this issue.

**Comment by SohanRC** [comment]
@apu52  Can This Background work ?? 
 Actually the thing is , the website is designed in such a way , that since the major part of the website is actually covered , the animations can not be seen in the background. I think animations such as solid linear gradient type will work here. 

Screenshot 2024-01-28 160929

**Comment by apu52** [comment]
> @apu52 Can This Background work ?? Actually the thing is , the website is designed in such a way , that since the major part of the website is actually covered , the animations can not be seen in the background. I think animations such as solid linear gradient type will work here.
> 
> Screenshot 2024-01-28 160929

I know... I think this is better .make all the changes & then make a PR then I will review it

**Comment by SohanRC** [comment]
OKK.

**Pull request closed without merging**
