### PR TITLE
feat: add effect on mentioned section

### LINKED ISSUE #964: [Feature Request]: add effect on mentioned section
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

image

in above section when the image is clicked its width is increased but not when it is hovered.

### Use Case

i would like to add the effect to preview an image which will be easier for user to decide if he/she want to click on it or not. 

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Rajput-xv**
Title : add effect on mentioned section 

Issue No. : #964

Code Stack : 

Close #964

# Description
Changes in Explore.js and Explore.css are made to achieve the hover effect on mentioned section & all the functionalities are added.

# Video/Screenshots (mandatory)

https://github.com/apu52/Travel_Website/assets/114978813/5fe07b39-2feb-4419-9722-ed875863179b

# Type of PR

- [X] Feature enhancement

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

##Are you contributing under any Open-source programme?

- [X] I am contributing under `GSSOC'24`

### CODE REVIEW

**Comment by Rajput-xv** [comment]
Hello @apu52 
Kindly look into this!!

**Review by apu52 — CHANGES_REQUESTED** [review]
@Rajput-xv this PR has merge conflicts .please try to resolve them faster so that I can review the code & will be able to merge it or submit a complete new PR to avoid the merging conflicts

**Comment by Rajput-xv** [comment]
> @Rajput-xv this PR has merge conflicts .please try to resolve them faster so that I can review the code & will be able to merge it or submit a complete new PR to avoid the merging conflicts

@apu52 
kindly look into this now.
conflicts are resolved.

**Comment by apu52** [comment]
> > @Rajput-xv this PR has merge conflicts .please try to resolve them faster so that I can review the code & will be able to merge it or submit a complete new PR to avoid the merging conflicts
> 
> @apu52 kindly look into this now. conflicts are resolved.

Conflicts still present in this PR

**Comment by Rajput-xv** [comment]
> > > @Rajput-xv this PR has merge conflicts .please try to resolve them faster so that I can review the code & will be able to merge it or submit a complete new PR to avoid the merging conflicts
> > 
> > 
> > @apu52 kindly look into this now. conflicts are resolved.
> 
> Conflicts still present in this PR

if you merge any other PR then it will always show conflicts on my PR as i have made changes.

now i have resolved the conflicts again kindly look into it.

@apu52

**Review by apu52 — CHANGES_REQUESTED** [review]
image


@Rajput-xv why this slider is opening up as like this please change the alignment & also the paris page is still in the bg of the slider .please try to rectify the bugs

**Comment by Rajput-xv** [comment]
> image
> 
> @Rajput-xv why this slider is opening up as like this please change the alignment & also the paris page is still in the bg of the slider .please try to rectify the bugs

will the slider in vertical position ?
as before i shared the video it was horizontal.
which alignment you want in your website ?

**Comment by apu52** [comment]
> > image
> > @Rajput-xv why this slider is opening up as like this please change the alignment & also the paris page is still in the bg of the slider .please try to rectify the bugs
> 
> will the slider in vertical position ? as before i shared the video it was horizontal. which alignment you want in your website ? @apu52

as u have shown in the video u have shared

**Comment by Rajput-xv** [comment]
> Title : add effect on mentioned section
> 
> Issue No. : #964
> 
> Code Stack :
> 
> Close #964
> 
> # Description
> Changes in Explore.js and Explore.css are made to achieve the hover effect on mentioned section & all the functionalities are added.
> 
> # Video/Screenshots (mandatory)
>  Travel.website.Recording.2024-07-07.190204.mp4 
> # Type of PR
> * [x]  Feature enhancement
> 
> # Checklist:
> * [x]  I have performed a self-review of my code.
> * [x]  I have commented my code, particularly in hard-to-understand areas.
> * [x]  I have tested the changes thoroughly before submitting this pull request.
> * [x]  I have provided relevant issue numbers, screenshots, and videos after making the changes.
> * [x]  I have gone through the  `contributing.md` file before contributing
> 
> ##Are you contributing under any Open-source programme?
> 
> * [x]  I am contributing under `GSSOC'24`

@apu52 
this was the original!
which i shared.
Now you want new or old one?

**Comment by Rajput-xv** [comment]
@apu52 
now alignment is corrected 
look into this & merge first, then conflicts may arise.
Thanks

**Comment by apu52** [comment]
image

everything is alright in the slider but this image is not loading .please try to check it

**Comment by Rajput-xv** [comment]
> image
> 
> everything is alright in the slider but this image is not loading .please try to check it

this is a preview of deployment u can see the url 

https://github.com/user-attachments/assets/d8b20000-1ad6-40b0-9546-5a6d42d792ce


as you can see the images are loading.
you can try to refresh the page.
@apu52

**Review by apu52 — APPROVED** [review]
@Rajput-xv good work

**Comment by Rajput-xv** [comment]
> @Rajput-xv good work

@apu52 
Thank you! I'm glad you found value in my work.

**Pull request merged**
