### PR TITLE
fix: Add valid email checker while subscribing

### LINKED ISSUE #1547: [Bug]: Check the email format while subscribing
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When users try to subscribe by entering their email, there is no validation or improper validation of the email format. As a result, users are able to enter incorrect or improperly formatted email addresses, causing issues with subscription or registration.

### Expected behavior

When users enter their email in the subscription form:

The email should follow the standard format, i.e., username@domain.com.
If the email format is incorrect, an error message should appear, prompting the user to enter a valid email.
The form should not be submitted until a properly formatted email is entered

### Add ScreenShots/Videos
Screenshot 2024-10-20 201308

### On which device are you experiencing this bug?

Browser: Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Ishika-Gupta06**
Title : valid Email while Subscribing

Issue No. : #1547 

Code Stack : html, JavaScript 

Close #1547 

# Description
improve the regex to ensure the domain part is properly validated (e.g., at least two characters after the dot).
Added an email validation regex (email Pattern) to check the input format.
If the email is valid, the success message is displayed.
If the email is invalid, an error message is displayed for 4 seconds.

# Video/Screenshots (mandatory)

https://github.com/user-attachments/assets/313757b3-5674-4068-b16a-e7f806f403f8

# Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing
- [X] I have Starred the Repository.

- [X] I am contributing under `GSSOC'24 Extended`
- [X] I am contributing under `Hacktoberfest'24`

### CODE REVIEW

**Comment by IRONalways17** [comment]
This pull request includes changes to the `index.html` file to improve the user experience and validation for the subscription form. The most important changes include adding an error message for invalid email addresses, improving the email validation regex, and refactoring the JavaScript code for better readability and functionality.

### User Experience Improvements:

* Added an error message to notify users when they enter an invalid email address. (`index.html` [index.htmlL1982-R1998](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L1982-R1998))

### Validation Enhancements:

* Improved the email validation regex to check for a valid domain. (`index.html` [index.htmlL1982-R1998](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L1982-R1998))

### Code Refactoring:

* Refactored JavaScript code to handle form submission more effectively by showing appropriate messages based on email validity. (`index.html` [[1]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L1982-R1998) [[2]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L2005-R2020)

**Comment by Ishika-Gupta06** [comment]
@apu52 please verify the PR

**Comment by Ishika-Gupta06** [comment]
@apu52 kindly review the PR

**Review by apu52 — APPROVED** [review]
@Ishika-Gupta06 good work

**Pull request merged**
