### PR TITLE
feat: Added social media links

### LINKED ISSUE #892: [Feature Request]: Adding social  media links in the footer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the footer there are no social media links 

### Use Case

When the user try to contact owner they dont see the quick links 

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
# Title and Issue number 

Title :Added social media links

Issue No. : #892 

Code Stack : 

Close #892 

# Description

I have added social media links 

# Video/Screenshots (mandatory)

image

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x ] I have performed a self-review of my code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [x ] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by Saipradyumnagoud** [comment]
@apu52  can you please review soon

**Comment by Saipradyumnagoud** [comment]
@itsekta  can you please review it 🙏🏾

**Review by apu52 — CHANGES_REQUESTED** [review]
@Saipradyumnagoud there is some recent changes in the website page so that your PR is facing some merging conflicts . so I would like to request you to submit a new PR making a new branch in your forked PR to avoid all of the conflicts
Otherwise the features u have added are working well .I have checked it

**Comment by Saipradyumnagoud** [comment]
@apu52 Now please go through the pull request

**Comment by itsekta** [comment]
Hey @Saipradyumnagoud, can you also improve the UI a little bit by adding gap between them, keep the icon color to white and on hovering over the icons change the color of the icons to their default icon instead of white only. Suppose Facebook icon color is blue (#1877F2) by default the icons are white only but on hovering over the facebook icon the color should be #1877F2. Similar for all the icons, checkout the colors for other icons as well

**Comment by Saipradyumnagoud** [comment]
> Hey @Saipradyumnagoud, can you also improve the UI a little bit by adding gap between them, keep the icon color to white and on hovering over the icons change the color of the icons to their default icon instead of white only. Suppose Facebook icon color is blue (#1877F2) by default the icons are white only but on hovering over the facebook icon the color should be #1877F2. Similar for all the icons, checkout the colors for other icons as well

Yes sure i will work on it

**Comment by Saipradyumnagoud** [comment]
image

**Comment by Saipradyumnagoud** [comment]
@apu52  @itsekta made the required changes requested

**Comment by itsekta** [comment]
@Saipradyumnagoud, why are the icons getting smaller on hover

**Comment by Saipradyumnagoud** [comment]
> @Saipradyumnagoud, why are the icons getting smaller on hover

Should i make icons bigger on hover

**Comment by itsekta** [comment]
Your choice, you can make a little bigger (scale 0.5) or don't just the ui should look nice.

**Comment by Saipradyumnagoud** [comment]
@itsekta yes now i have made please check

**Comment by itsekta** [comment]
Nice

**Comment by Saipradyumnagoud** [comment]
> Nice 

@itsekta  can you please merge the pull request

**Comment by itsekta** [comment]
@apu52 will be merging it

**Comment by Saipradyumnagoud** [comment]
> @apu52 will be merging it

Yes make it soon

**Pull request merged**
