### PR TITLE
feat: added the packages page

### LINKED ISSUE #1297: [Feature Request]: Making a new page Popular Packages
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will place the hotel and travel packages there
In the navbar I will add the link to page popular packages
In the section there will be only one photo below which there will be a button "See all Packages"

On clicking the user will be able to see the of them listed

### Use Case

I will place the hotel and travel packages there
In the navbar I will add the link to page popular packages
In the section there will be only one photo below which there will be a button "See all Packages"

On clicking the user will be able to see the of them listed

### Benefits

**Reducing main page content overcrowding**

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by ayush-848**
# Title and Issue number 

Title : added the packages page

Issue No. : #1297

Code Stack : HTML, CSS, JS

Close #1297

# Description

- added a packages page
- added the navbar in it
- added trips, hotel and pricing sections
- added a video background with a proper overlay
- added few fade and hover effects

# Video/Screenshots (mandatory)
https://www.awesomescreenshot.com/video/30174347?key=af98b0f456970bdcc93d9e643a9e9e02

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by ayush-848** [comment]
@apu52 please check this. I have put a lot of efforts in the layout and styling

**Review by apu52 — CHANGES_REQUESTED** [review]
image

all the changes u have made are really good . But the pricing in the INR section is not showing up properly. please try to fix this issue .

**Comment by ayush-848** [comment]
> image
> 
> all the changes u have made are really good . But the pricing in the INR section is not showing up properly. please try to fix this issue .

Ok

**Comment by ayush-848** [comment]
image
@apu52 I will fix the pricing and functionalities and links every thing in #1318

**Comment by ayush-848** [comment]
@apu52 for now merge this PR

**Pull request merged**
