### PR TITLE
feat: add dark mode feature in guide page

### LINKED ISSUE #1153: [Feature Request]:  ADD DARK MODE IN BOOK NOW/GUIDE PAGE
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

ADD DARK MODE IN BOOK NOW/GUIDE PAGE

### Use Case

GOOD VISIBILITY IN DARK MODE

### Benefits

ADD DARK MODE IN BOOK NOW/GUIDE PAGE

### Add ScreenShots

https://github.com/user-attachments/assets/ab3492ce-b1db-459f-ba9b-31baeedddd23

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by ANKeshri**
# Title and Issue number 

Title : add dark mode feature in guide page

Issue No. : #1153 

Code Stack : html css and js

Close #1153 

# Description

add dark mode feature in guide page 

# Video/Screenshots (mandatory)

https://github.com/user-attachments/assets/881d9928-ce5d-435a-8ac7-6cf132844b57

# Type of PR

- [X] Feature enhancement

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [X] I am contributing under `GSSOC'24`

### CODE REVIEW

**Comment by ANKeshri** [comment]
@apu52 please review and merge my pr

**Review by apu52 — CHANGES_REQUESTED** [review]
@ANKeshri the color scheme of the dark mode of the booking page u have added is not matching with the other parts of the website & also it's not catchy for the users also , please try to improve it with better UI

**Comment by ANKeshri** [comment]
https://github.com/user-attachments/assets/157b7621-1de1-4110-9ca3-7d2e8312dc2a

@apu52 please review and merge it

**Review by apu52 — APPROVED** [review]
@ANKeshri good work

**Pull request merged**
