### PR TITLE
fix: Fixed Hamburger

### LINKED ISSUE #1093: Hamburger button not working in the Membership page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The hamburger button should work. Currently it only appears, but pressing it dosen't trigger any action,

### Use Case

This would be useful when user is in mibile-devices

### Benefits

By making the button working, users on mobile devices will be able to easily navigate with ease.

### Add ScreenShots

The button appears, but doesn't work
image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by VijaySamant4368**
# Title and Issue number 

Title : Fixed Hamburger

Issue No. : #1093

Code Stack : 

Close #1093

# Description

The Hamburger now works in the Membership page

# Video/Screenshots (mandatory)

image

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by VijaySamant4368** [comment]
@sau-mili please kindly check the pr.

**Comment by VijaySamant4368** [comment]
@itsekta @apu52 please kindly check this pr.

**Comment by VijaySamant4368** [comment]
@itsekta @apu52 please kindly check this pr.

**Review by apu52 — APPROVED** [review]
@VijaySamant4368 good work

**Pull request merged**
