### PR TITLE
feat:updated style.css

### PR DESCRIPTION
**Pull request by Niharika-Upveja**
feat:updated style.css

# Title and Issue number 
Title :Enhanced responsivness

Issue No. : https://github.com/apu52/Travel_Website/issues/137

[Screencast from 22-01-24 11:40:25 PM IST.webm](https://github.com/apu52/Travel_Website/assets/127125259/0fb1e810-1e1a-4101-856e-a7934ca22b7f)

Close : #137

### CODE REVIEW

**Comment by Niharika-Upveja** [comment]
@apu52 Please Review

**Comment by Niharika-Upveja** [comment]
@apu52 Please Review

**Review by apu52 — APPROVED** [review]
OK

**Comment by apu52** [comment]
@Niharika-Upveja Thanks for your valuable contribution.

**Comment by apu52** [comment]
@Niharika-Upveja Can you please share your full name so that I can update the leaderboard

**Pull request merged**
