### PR TITLE
feat: custom cursor added (issue : #772)

### LINKED ISSUE #772: Feature_Request: Custom cursor
**Is your feature request related to a problem? Please describe.**

The website looks awesome, but it can be even more attractive and professional if there is a custom cursor which syncs to the website design.

**Describe the solution you'd like**

I would like to add the custom cursor with not only syncs with the website design but also with the motion after cursor movement effect.

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**

***Are you contributing under any open-source program ?***

GSSOC'24

### PR DESCRIPTION
**Pull request by chaanakyaaM**
# Title and Issue number 

Title :Custom Cursor

Issue No. : #772 

Code Stack : HTML, CSS , JS

Close #772 

# Description

 I have added the custom cursor.

# Video/Screenshots (mandatory)

https://github.com/apu52/Travel_Website/assets/131477601/d560a39c-296a-4b7f-b977-e1504a4e5e30

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing
<!- [X] - put a cross/X inside [] to check the box -->

# Additional context:

##Are you contributing under any Open-source programme?

GSSOC'24

### CODE REVIEW

**Comment by chaanakyaaM** [comment]
Let me know if there are any changes to be made.

**Comment by chaanakyaaM** [comment]
would do please review this PR.

**Comment by chaanakyaaM** [comment]
Please review this PR.

**Review by apu52 — CHANGES_REQUESTED** [review]
@chaanakyaaM  there is some recent changes in the website page so that your PR is facing some merging conflicts . so I would like to request you to submit a new PR making a new branch in your forked PR to avoid all of the conflicts
Otherwise the features u have added are working well .I have checked it

**Comment by chaanakyaaM** [comment]
Sure

**Comment by chaanakyaaM** [comment]
@apu52  kindly review this PR.

**Review by apu52 — CHANGES_REQUESTED** [review]
@chaanakyaaM this PR still have merge conflicts & Just I have notices that tis website already has a custom Cursor . So I think There is no need for this PR now .Hope u will understand .I want to suggest u to close this PR & look forward for farther more issues in this project.

**Comment by chaanakyaaM** [comment]
sure

**Pull request closed without merging**
