### PR TITLE
fix: made navbar uniform across all pages

### LINKED ISSUE #1626: [Bug]: Navbar styling is not consistent across all pages
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The navbar styling is not consistent across all pages. The font size, colors, and alignment of the navbar vary depending on the page, which creates a disjointed user experience. Some pages show different spacing or background colors in the navbar, making it appear unpolished.

### Expected behavior

The navbar should have a uniform style across all pages, with consistent font size, colors, alignment, and spacing. Users should experience a seamless transition when navigating from one page to another without any changes in the navbar's appearance.

### Add ScreenShots/Videos

Screenshot 2024-11-05 005942
Screenshot 2024-11-05 010149

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by shivam8112005**
# Title and Issue number 

Title :made navbar uniform across all pages

Issue No. :  #1626 

Code Stack : html, css

Close #1626 

# Description

This PR standardizes the navbar styling across all pages by ensuring uniform spacing, sizing, and hover effects. It also enhances mobile responsiveness with a cohesive design, improving the overall user experience.

# Video/Screenshots (mandatory)

Screenshot 2024-11-06 004758
Screenshot 2024-11-06 004803
Screenshot 2024-11-06 004808

# Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing
- [X] I have Starred the Repository.

# Additional context:

##Are you contributing under any Open-source programme?

- [X] I am contributing under `GSSOC'24 Extended`
- [X] I am contributing under `Hacktoberfest'24`

### CODE REVIEW

**Comment by shivam8112005** [comment]
@apu52 done.

**Comment by shivam8112005** [comment]
@apu52  can you please review this?

**Review by apu52 — CHANGES_REQUESTED** [review]
@shivam8112005 on many of the pages where u have edited the navbar u have deleted the logo of the website , please try to revert that commit & also whenever I will click on the navbar (like top deals , about etc.)& it will redirect to the other pages but the hamburger is not working well on that pages responsiveness  , please try to fix that also

**Comment by shivam8112005** [comment]
@apu52 ohk

**Comment by apu52** [comment]
@shivam8112005 have u solves the issue what I have suggested u in the comments?

**Comment by shivam8112005** [comment]
@apu52  Not yet i will do that by 13 currently i am traveling

**Pull request closed without merging**
