### PR TITLE
edited login page and added aboutUs

### LINKED ISSUE #117: Feature_Request: Addition of  "About Us" in navigation bar
**Is your feature request related to a problem? Please describe.**

we can add an information block of  website in navigation bar.

**Demo Video/Screenshot (Mandatory )**
Screenshot 2024-01-21 095357

***Are you contributing under any open-source program ?***

Yes Under JWOC 2024

### PR DESCRIPTION
**Pull request by shreya9x1**
# Title and Issue number 

Title :edited login page and navbar

Issue No. :#117

Code Stack : HTML CSS

Close #117

# Video/Screenshots (mandatory)

Screenshot 2024-01-27 214153

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***
Under JWOC'24

### CODE REVIEW

**Review by apu52 — APPROVED** [review]
Really great contribution. Thanks @shreya9x1 for all of your efforts & patience , hardwork

**Comment by apu52** [comment]
@shreya9x1 Can you tell me your full name so that I can update the leaderboard

**Comment by shreya9x1** [comment]
Thank you sir for merging it finally and my name is Shreya Pandey

**Comment by shreya9x1** [comment]
As it was my first contribution, I learnt so many things specially git
commands.

**Pull request merged**
