### PR TITLE
Resolved the problem in "AboutUs" section

### LINKED ISSUE #117: Feature_Request: Addition of  "About Us" in navigation bar
**Is your feature request related to a problem? Please describe.**

we can add an information block of  website in navigation bar.

**Demo Video/Screenshot (Mandatory )**
Screenshot 2024-01-21 095357

***Are you contributing under any open-source program ?***

Yes Under JWOC 2024

### PR DESCRIPTION
**Pull request by shreya9x1**
# Title and Issue number 

Title :#resolved the problem of "About Us"

Issue No. :#117

Code Stack : Screenshot 2024-01-25 215041

Close #117

# Video/Screenshots (mandatory)

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***
 
Yes JWOC'24

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
image

This picture must be attached with the login part .

**Comment by apu52** [comment]
@shreya9x1 just make this changes . then I can merge your PR otherwise the other  commits are fine.

**Comment by shreya9x1** [comment]
@apu52  it should be attached with only login part or both?

**Comment by shreya9x1** [comment]
@apu52  Sir I request, kindly merge it for now. Its been so long that I'm working for this PR

**Comment by shreya9x1** [comment]
@apu52  Sir,Kindly Merge it for now, I have been working on this repo from so long.

**Comment by apu52** [comment]
> @apu52 Sir, Kindly Merge it for now, I have been working on this repo from so long. And I have updated the login page kindly check once

@shreya9x1 I really can't merge it as the PR consist of MERGE conflicts. I  can suggest you to make a separate branch in your forked repo & make all the changes there

**Pull request closed without merging**
