### PR TITLE
feat: Improved UI of FAQ page to match website theme

### LINKED ISSUE #986: [Feature Request]:UI of FAQ page to match website theme
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The UI of FAQ does not matches with the overall theme of webiste.

### Use Case

Can added the images and animation so that is looks good and increase users engagement.

### Benefits

_No response_

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by TBorundia**
# Title and Issue number 
Title : Improved UI of FAQ page to match website theme

Issue No. : #986

Code Stack : 

Close #986

# Description
Improved UI to match website theme.
Made the page responsive too.

# Video/Screenshots (mandatory)

https://github.com/apu52/Travel_Website/assets/168854094/64c03a28-8e0d-4f12-a651-60134ed65b77

https://github.com/apu52/Travel_Website/assets/168854094/a7928b70-29d1-417c-9a93-8b3dbc423d7c

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X]  I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X]  I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by TBorundia** [comment]
@apu52 @itsekta , please review this PR.
Thank You!

**Comment by TBorundia** [comment]
@apu52 @itsekta , please review this PR.
Thank You!

**Comment by TBorundia** [comment]
@apu52  Sir, please review this PR.
Thank You!

**Comment by apu52** [comment]
@TBorundia is there any problem that u have closed this PR as I was reviewing this PR & suddenly it is closed

**Comment by TBorundia** [comment]
@apu52  Sir, I am experiencing an issue with the background image not displaying correctly. 
I will reopen the task and would appreciate your feedback on whether it appears the same for you. 
If the issue persists, I will open a new PR.
Thank you.

**Review by apu52 — CHANGES_REQUESTED** [review]
@TBorundia exactly as u have suggested , the website is really looking messy in your PR . So I would like to better suggest u to submit a new PR making a new branch & push all of your changes there in your forked repo & please close this PR

**Pull request closed without merging**
