### PR TITLE
feat: Made the changes for the google transulate 

### LINKED ISSUE #1007: [Feature Request]: Adding Style for the google transulate
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding styles for the transulate in the footer

### Use Case

image

adding the styles

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
# Title and Issue number 

Title :Made the changes for the google transulate 

Issue No. : #1007 

Code Stack : HTML CSS JS

Close #1007 

# Description

Added Google Transulate And styled it Properly

# Video/Screenshots (mandatory)

image

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by Saipradyumnagoud** [comment]
@apu52 @itsekta You can please Review it now i have made it as you told @apu52

**Review by apu52 — CHANGES_REQUESTED** [review]
@Saipradyumnagoud sorry to say , the UI of the google translator is not looking up to the mark . like its not matching with the UI of the website .please think some other alternatives.

**Comment by Saipradyumnagoud** [comment]
@apu52 Can you Once please Review for any chages

image

here is the new transulate

**Comment by apu52** [comment]
@Saipradyumnagoud all things are working perfect just add "GOOGLE" logo after powered by

**Comment by Saipradyumnagoud** [comment]
@apu52 I have added google logo after powerd by

**Review by apu52 — APPROVED** [review]

**Comment by apu52** [comment]
@Saipradyumnagoud good work & as u already have dedicated a lot of time in this PR , I am assigning u "LAVEL 2"

**Comment by Saipradyumnagoud** [comment]
> @Saipradyumnagoud good work & as u already have dedicated a lot of time in this PR , I am assigning u "LAVEL 2"

@apu52 Really very thank you

**Pull request merged**
