### PR TITLE
feat: dark mode in membership page

### LINKED ISSUE #1214: [Feature Request]: dark mode for membership page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

dark mode for membership page 

### Use Case

good visibility 

### Benefits

new feature to the page 

### Add ScreenShots

https://github.com/user-attachments/assets/9881c98f-9684-45eb-be1e-aab0014c8602

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by ANKeshri**
# Title and Issue number 

Title :  dark mode in membership page

Issue No. :#1214

Code Stack : 

Close #1214

# Description

dark mode feature in membership page 

# Video/Screenshots (mandatory)

https://github.com/user-attachments/assets/5ac71d4d-122a-4d8d-bac3-12c3270e74eb

# Type of PR

- [X] Feature enhancement

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [X] I am contributing under `GSSOC'24`

### CODE REVIEW

**Comment by ANKeshri** [comment]
@apu52 please review once and merge my pr

**Review by apu52 — CHANGES_REQUESTED** [review]
@ANKeshri the color scheme of the dark mode of the booking page u have added is not matching with the other parts of the website & also it's not catchy for the users also , please try to improve it with better UI

**Comment by ANKeshri** [comment]
@apu52 can you please suggest me what changes you want as i have given same toggke for dark and light mide and in no particular pahe there is dark mode from where i could take reference

**Comment by apu52** [comment]
@ANKeshri please try to look at the UI of the main website at dark mode check the color schemes . You can take reference from that . Actually In the dark mode u have made it's simply black color UI so I wanted u to enhance it .

**Comment by ANKeshri** [comment]
@apu52 made the dark mode according to theme (taken refernce from home page testionial)

image

**Review by apu52 — APPROVED** [review]
@ANKeshri good work

**Pull request merged**
