### PR TITLE
Feature_Request : Make a Different Login Page #26

### LINKED ISSUE #26: Feature_Request : Make a Different Login Page
**Is your feature request related to a problem? Please describe.**

Hello All,
You can make a different login page in this project 

**Describe the solution you'd like**

It  will help the users to login with their
- mail
- facebook
- google account
& also made a button in the front pg as clickable to jump into that page

**Describe alternatives you've considered**

you can use JS or react to make this with added HTML& CSS.

**Demo Video/Screenshot (Mandatory )**

image

This is just a Demo. You can make it more fascinating & working

***Are you contributing under any open-source program ?***

JWOC 2k24

### PR DESCRIPTION
**Pull request by Sneha6003**
Feature_Request : Make a Different Login Page #26

Title : Feature_Request : Make a Different Login Page #26

Issue No. : #26

Code Stack :  HTML, CSS

Close #26 

# Video/Screenshots (mandatory)

image
image

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

I hope it will work now, Thank You for guiding me!

***Are you contributing under any Open-source programme?***

### CODE REVIEW

**Review by apu52 — APPROVED** [review]
Ok

**Comment by apu52** [comment]
@Sneha6003 Thank you for your valuable contribution

**Comment by apu52** [comment]
@Sneha6003 Can you please share your full name here , so that I can update the leaderboard

**Comment by Sneha6003** [comment]
@apu52 
Name: Sneha Singh
Username: Sneha6003

**Pull request merged**
