### PR TITLE
feat: Created a pop up for discount for trip packages webpage

### LINKED ISSUE #886: A side pop up for discount on Trip packages webpage
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A side pop up for discount on Trip packages webpage. This side pop up can contain a discount applied when particular code is entered.

### Use Case

The side pop up can be used as for applying discount.

### Benefits

Like this:

### Add ScreenShots

Screenshot 2024-06-18 at 7 27 27 PM

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by suhanigupta23**
# Title and Issue number 
Close #886 

Code Stack : 
 HTML, CSS , JS used 

# Description

created a pop up for discount for trip packages webpage. The pop up appears after 5 seconds of loading the webpage to appear it as a pop up. Also a close button is also available in the top right corner to close the pop up.

# Video/Screenshots (mandatory)

Screenshot 2024-06-28 at 6 09 46 PM

# Type of PR

- [x] Feature enhancement

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

# Additional context:
Please tell if any changes required.

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@suhanigupta23 this PR has merging conflicts .Please try to resolve the conflicts so that I can review /merge the PR . Or best thing u can submit a total new PR (making a new branch in your PR) to avoid the conflicts

**Review by apu52 — APPROVED** [review]
@suhanigupta23 okkk . well made changes

**Comment by apu52** [comment]
@suhanigupta23 have u done all of your changes in the PR , Can I merge it now ?? or any other changes left??

**Comment by suhanigupta23** [comment]
@apu52 Yes please merge . Let me know if any more css changes or any required .

**Comment by apu52** [comment]
> @apu52 Yes please merge . Let me know if any more css changes or any required .

no .it's fine

**Pull request merged**
