### PR TITLE
fix: Added social media profile urls in feedback page.

### LINKED ISSUE #1364: [Bug]: The social media links are not working on feedback page.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

-  The social media links are not working on feedback page.

### Expected behavior

- The social media links should redirect to correct social media profile url when clicked.

### Add ScreenShots

https://github.com/user-attachments/assets/024328c6-2208-409f-872a-b98aa87a9150

### On which device are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by vishanurag**
# Title and Issue number 

Title :  _Added social media profile urls in feedback page_

Issue No. : #1364 

Code Stack : HTML

Close #1364 

# Description
- Added social media profile urls in feedback page.
- Now, the social media profiles will open when clicked on these icons.

# Video/Screenshots (mandatory)

https://github.com/user-attachments/assets/60a8fcb3-28c4-4379-8f07-d06543f4e248

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

# Additional context:

@apu52 please review & merge my pull-request under GSSoC'24

## Are you contributing under any Open-source programme?

Yes, GSSoC'24

- [x] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by vishanurag** [comment]
There is some issue with the video recorder...

**Comment by vishanurag** [comment]
> There is some issue with the video recorder...

https://github.com/user-attachments/assets/c338f9a1-7ee1-4b2a-b494-47f3b197f50b

@apu52 @itsekta 
This is the output...

**Review by apu52 — APPROVED** [review]
@vishanurag good work

**Comment by vishanurag** [comment]
@apu52 can you  please add level label on this pr 🙏

**Comment by vishanurag** [comment]
Because without level label I will not be able to get the points of this pr in GSSOC'24. Hope you understand 🙏

**Pull request merged**
