### PR TITLE
Feedback Page and Login Page fixed

### LINKED ISSUE #469: Feature_Request:  Added missing Navbar on the feedback page
**Is your feature request related to a problem? Please describe.**

the Navbar was missing in the feedback section  and unable to navigate back so , itis important to add Navbar to feedback page also

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
before screenshot
Screenshot (1692)

after updating

Screenshot (1693)

***Are you contributing under any open-source program ?***
yes girlscript summer of code (Gssoc'24)

### PR DESCRIPTION
**Pull request by SadafKausar2025**
# Feedback Page and Login Page  fixed  and: #469

Title :

Issue No. :#469

Code Stack : 

Close #469 

https://github.com/apu52/Travel_Website/assets/137484958/fe29cfb1-261a-43ec-a261-d58db399f808

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
hi @apu52 
i corrected both page feedback and login page
I see that there was issue in linking the styles file

now it is all correct

**Comment by SadafKausar2025** [comment]
and also Navbar of both page is working properly

**Comment by SadafKausar2025** [comment]
Hi @apu52 
i have created another new PR with all correct changes please assign me

**Review by apu52 — COMMENTED** [review]
@SadafKausar2025 I am closing this PR as this has merge conflicts . Due to recent changes in the repo this PR is facing merge conflicts . Please make a new PR so that I can merge the PR by updating/syncing the branch in your forked repo to the latest updated version of the repo

**Comment by SadafKausar2025** [comment]
hey @apu52 
conflict can be resolved here only 
please reopen the PR?

**Pull request closed without merging**
