### PR TITLE
feat: Update plantrip.html

### LINKED ISSUE #1261: [Feature Request]: Improve Plan a trip page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The UI is neither responsive, nor readable
It needs a lot of improvement

### Use Case

Better readability and format

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by sau-mili**
# Title and Issue number 

Title : Updated plan a trip page

Issue No. : #1261

Code Stack :  HTML, CSS, JS

Close #1261 

# Description

# Video/Screenshots (mandatory)

Screenshot 2024-07-30 220953

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
image

the UI of the plan trip page is not looking professional , please try to enhance the UI

**Comment by sau-mili** [comment]
Okay. I will update it by tomorrow

**Comment by sau-mili** [comment]
Please check now. I have Updated the page.
- added new background
- new navbar
- form UI updated
- added caution if not input is added
- added a trip suggesting carousel
Screenshot 2024-08-05 014041
Screenshot 2024-08-05 014052
Screenshot 2024-08-05 014106
Screenshot 2024-08-05 014120

**Comment by apu52** [comment]
@sau-mili this pR has some merge conflicts , please try to resolve the conflicts , so that I can review the code & will be able to merge the PR.

**Comment by sau-mili** [comment]
i will resolve it in 5 minutes

**Comment by sau-mili** [comment]
Please check now

**Review by apu52 — APPROVED** [review]

**Pull request merged**
