### PR TITLE
Local installation video

### LINKED ISSUE #182: [Feature]: Enhance Contributor Onboarding -Add Local Installation Video to README
**Is your feature request related to a problem? Please describe.**
Contributor onboarding could be improved by providing a visual guide on how to install the project locally. Adding a video demonstration will help newcomers understand the setup process more effectively.

**Describe the solution you'd like**
A short video covering the following:

Cloning the repository.
Installing dependencies.
Configuring any necessary settings.
Running the project locally.

**Demo Video/Screenshot (Mandatory )**
A link

***Are you contributing under any open-source program ?***
Yes, under JWOC.

### PR DESCRIPTION
**Pull request by rahat2134**
Title :Local installation video

Issue No. : #182 

Code Stack : Video

Close #182 
# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

Screenshot->
image
image

***Are you contributing under any Open-source programme?***

under JWOC.

### CODE REVIEW

**Comment by rahat2134** [comment]
@apu52 PTAL.

**Review by apu52 — CHANGES_REQUESTED** [review]
Can you please attach the Video in the PR so that I can review it @rahat2134

**Comment by apu52** [comment]
@rahat2134 Update your demo video/prototype in the PR .

**Comment by rahat2134** [comment]
> @rahat2134 Update your demo video/prototype in the PR .

updating ,

**Comment by rahat2134** [comment]
> > @rahat2134 Update your demo video/prototype in the PR .
> 
> updating ,

updated screenshot, not able to upload video.

**Review by apu52 — APPROVED** [review]

**Pull request merged**
