### PR TITLE
feat: Enhancing About Section

### LINKED ISSUE #1084: Enhancing About Section
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Would like to add a background to ABOUT section as it seems simple compared to rest of the website.

### Use Case

This would enhance the look of the  website making it visually appealing to the viewers.

### Benefits

_No response_

### Add ScreenShots

Screenshot 2024-07-15 233604

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by AshmitaBarthwal**
# Title and Issue number 

Title : Enhancing About Section

Issue No. : #1084

Code Stack : CSS

Close #1084

# Description
Made FINAL changes asked by you.

# Video/Screenshots (mandatory)
UPDATED :

https://github.com/user-attachments/assets/cf844e70-7254-4acb-bf2c-b8bd7c4e923f

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [X] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by AshmitaBarthwal** [comment]
@apu52 I HAVE CREATED A NEW PULL REQUEST TO AVOID MERGE CONFLICTS.
AND I HAVE DONE ALL REQUIRES CHNAGES.
PLEASE REVIEW MY PR ONCE

**Comment by AshmitaBarthwal** [comment]
@itsekta I have made all changes that were asked in my previous pull request.
i created a new pull request to avoid any merge conflicts.
please review it once.

**Comment by itsekta** [comment]
@AshmitaBarthwal, For the About Us section, ensure that the color combination matches the current UI, as the colors you used are not suitable.

**Comment by AshmitaBarthwal** [comment]
@itsekta But it was approved earlier.

**Comment by itsekta** [comment]
The background color can be improve as you scroll down the website the red gradient you have used looks a little bold. Just try to improve it with something bluish or a light color

**Comment by apu52** [comment]
> @itsekta How's This??
> 
> Screenshot 2024-07-20 163903

it's okay .Now apply this commit in this PR so that I can merge it

**Comment by AshmitaBarthwal** [comment]
@apu52 okay I am making these changes.

**Comment by AshmitaBarthwal** [comment]
@apu52 MADE ALL DESIRED CHNAGES.

**Comment by AshmitaBarthwal** [comment]
@apu52 PLEASE REVIEW IT ONCE.

**Review by itsekta — APPROVED** [review]
The UI looks better now

**Review by apu52 — CHANGES_REQUESTED** [review]
@AshmitaBarthwal there is some merge conflicts present in this PR .please try to resolve the conflicts so that I can review the PR & merge it

**Review by apu52 — CHANGES_REQUESTED** [review]
@AshmitaBarthwal why this commit present here ?? Please try to delete the unnecessary commits which is not linked with this pR

**Comment by AshmitaBarthwal** [comment]
Okay I Will Do the Changes. Will delete extra things

**Comment by AshmitaBarthwal** [comment]
@apu52 I have deleted the unecessary files.
please review it once.

**Comment by AshmitaBarthwal** [comment]
@apu52 Now review this update PR

**Comment by AshmitaBarthwal** [comment]
@apu52 what should i do to resolve them?? i am unable to fix it.

**Comment by apu52** [comment]
> @apu52 what should i do to resolve them?? i am unable to fix it.

Then I will suggest you to close this current PR & submit a new PR making a new branch in the forked repo & then push your commits there

**Comment by AshmitaBarthwal** [comment]
@apu52 i am trying to resolve it if it didn;t happen then i will create a new PR

**Comment by AshmitaBarthwal** [comment]
@apu52  ALL MERGE CONFLICTS RESOLVED.

**Comment by AshmitaBarthwal** [comment]
@apu52 please check it once, if any issue arises i will fix that.

**Review by apu52 — APPROVED** [review]

**Comment by apu52** [comment]
@AshmitaBarthwal good work

**Pull request merged**
