### PR TITLE
fix: Redirecting to the desired url instead of /story page.

### LINKED ISSUE #1021: [Bug]: Redirecting to /story page instead of the desired url
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On landing page when the popup modal appears and clicking on **close icon** it is redirecting to /story page instead of the main landing page and while on the /story page clicking on any navigation link it is still redirecting to /story page instead of the link that we have clicked. This thing doesn't happens with which click on **no thanks** on the modal.

https://github.com/apu52/Travel_Website/assets/60789158/e84f194c-c609-43ef-b34a-4d26cfdeb67e

Anyone interested can solve this bug.

### Expected behavior

Similar to when clicked on **no thanks** on the popup modal when clicked on the **close icon** on that modal should not redirect us to /story page and same for the other links as well

### Add ScreenShots

Main Landing page

image

When clicked on **close icon** on popup modal

image

### On which device are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by meetarora10**
# Title and Issue number 
Title :Redirecting to /story page instead of the desired url.

Issue No. : #1021

Code Stack : HTML,JavaScript

Close #1021

# Description
Now on click of the close icon on the window , main landing page is opened instead of story page . Also all the other corresponding links are opened on click of the tabs on navbar.

# Video/Screenshots (mandatory)

https://github.com/apu52/Travel_Website/assets/143121854/45e624d1-d946-4edd-8cdf-0f48e21468ab

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?
Yes under GSSoC'24.

- [x] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@meetarora10 this PR has merge conflicts .please try to resolve them faster so that I can review the code & will be able to merge it or submit a complete new PR to avoid the merging conflicts

**Comment by meetarora10** [comment]
> @meetarora10 this PR has merge conflicts .please try to resolve them faster so that I can review the code & will be able to merge it or submit a complete new PR to avoid the merging conflicts

@apu52 okay I will do now.

**Comment by meetarora10** [comment]
@apu52 please review this as well

**Review by apu52 — CHANGES_REQUESTED** [review]
image

by the changes u have made in the div class of the story page the story page is not existing in this PR .please try to rectify that & also by managing that try to resolve the issue

**Comment by meetarora10** [comment]
Okay @apu52

**Comment by meetarora10** [comment]
Done @apu52

**Review by apu52 — APPROVED** [review]
@meetarora10 good work

**Pull request merged**
