### PR TITLE
fix: Improved CSS

### LINKED ISSUE #1117: [Bug]: CSS mistake
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The 'Book Now' button and the card below it are overlapping, in three places which is resulting in an ugly interface.

### Expected behavior

There should be enough vertical distance between them.

### Add ScreenShots

image
image
image

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by VijaySamant4368**
# Title and Issue number 

Title : Improved CSS code in the hotel booking section

Issue No. : #1117

Code Stack : 

Close #1117 

# Description

Improved the CSS, by using CSS flexbox, and removed the unnecessary \<br> elements.

# Video/Screenshots (mandatory)

Before Changes:
image

After changes:
image
image

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by VijaySamant4368** [comment]
@sau-mili please kindly check the pr.

**Review by itsekta — APPROVED** [review]
The changes look good

**Comment by VijaySamant4368** [comment]
@itsekta can I get level-2 GSSoC label?

**Comment by VijaySamant4368** [comment]
@itsekta can you please merge this pr?

**Comment by VijaySamant4368** [comment]
@apu52  @itsekta can you please merge this pr?

**Comment by apu52** [comment]
@VijaySamant4368 thanks for your valuable contribution .

**Comment by VijaySamant4368** [comment]
@apu52, can I get a level 2 label?

**Pull request merged**
