### PR TITLE
feat: enhancement of trending page

### LINKED ISSUE #1440: [Feature Request]: Enhancement of the trending page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The trending page did not set well with the websites concept so I have enhanced it to make it readable

### Use Case

I will enhance the feature by adding background color and also alignment of the cards 

### Benefits

This will make it even more user friendly

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Ananya-vastare**
Close #1440

Background Update: Added a distinct background section for an improved visual effect, enhancing the page’s aesthetic.

Header and Subheader Styling:

Changed the main heading to a prominent black color for better readability.
Added a descriptive subheading to inspire confidence and provide an inviting overview of the tours.
Tour Card Layout:

Organized destinations into individual, uniform cards with images, names, and links for a cleaner and more structured presentation.
Buttons for Easy Navigation:

Added a Blog Page button on each card for quick access to detailed blogs on individual destinations.
Included a View all tours button to lead users to the full list of tour packages.
Responsive Design:

Structured the page for compatibility across various devices, ensuring a smooth experience for users on both desktop and mobile.
Consistent Visual Styling:

Ensured uniform size and alignment for all elements to create a cohesive and professional appearance.
Change1

### CODE REVIEW

**Comment by Ananya-vastare** [comment]
Change

**Comment by Ananya-vastare** [comment]
> feat: Create a new trending page

what changes should I make I am having trouble with the pr changes

**Comment by Ananya-vastare** [comment]
> > feat: Create a new trending page
> 
> what changes should I make I am having trouble with the pr changes

**Review by apu52 — CHANGES_REQUESTED** [review]
@Ananya-vastare I have gone through your changes . please try to fill up the pr form correctly with all the pic/ video prototype of the changes u have made .Please try to fill that up correctly so that I can merge this pr.

**Comment by Ananya-vastare** [comment]
@apu52 by end of the day I will do the changes

**Comment by Ananya-vastare** [comment]
@apu52 plese add the label and level to this thank you

**Review by apu52 — APPROVED** [review]
@Ananya-vastare good work . just from next time please try to use the already given pr template to submit your pr.

**Pull request merged**
