### PR TITLE
feat: UI Enhancement and Bug Fixed in Story Page

### LINKED ISSUE #1027: [Bug]:  UI Enhancement and Bug Fixes in Story Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @apu52 and @itsekta 

The story page has so many bugs and alignment issues also it does not match the website design theme 

image

Could you please assign this issue to me under GSSOC24?

### Expected behavior

N/A

### Add ScreenShots

_No response_

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by RadhikaMalpani1702**
# Description

Hey @apu52 
-  issue closes #1027 

I have enhanced the UI and fixed the bug in the story page

# Video/Screenshots (mandatory)

image

image

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [X] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

### CODE REVIEW

**Comment by RadhikaMalpani1702** [comment]
@apu52 Please merge it

**Comment by RadhikaMalpani1702** [comment]
@apu52 Please merge this PR

**Review by apu52 — CHANGES_REQUESTED** [review]
@RadhikaMalpani1702 there is some merge conflict as I can see present in this PR , please try to fix that conflicts so that I can review the code & also be able merge it.

**Review by apu52 — APPROVED** [review]
@RadhikaMalpani1702 good work

**Pull request merged**
