### PR TITLE
Added missing Navbar on the feedback page

### PR DESCRIPTION
**Pull request by SadafKausar2025**
# Title and Issue number 

Title :

Issue No. :

Code Stack : 

Close #<issue_no>

# Video/Screenshots (mandatory)

# Checklist:

- [ ] I have mentioned the issue number in my Pull Request.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
Also given margin from top and bottom of feedback page now it looks better

**Comment by SadafKausar2025** [comment]
original page : without Navbar on Rating page

Screenshot (1692)

After updating

Screenshot (1693)

**Comment by SadafKausar2025** [comment]
can you Please assign this issue to me?

**Review by apu52 — COMMENTED** [review]
@SadafKausar2025 I think you haven't raised issues before making the PR . I would like to recommend you to raise issues first & then only after getting assigned Please submit your PR. Sorry to close this PR

If you have already  raised any issue regarding this previously already & have get assigned , then please mention it here So that I can reopen the PR again

**Comment by SadafKausar2025** [comment]
yes I have created the issue and issue no is #469?
can you please assign this issue #469 to me?
and merge this PR

**Comment by SadafKausar2025** [comment]
hi @apu52 
please reopen this PR

**Comment by apu52** [comment]
> hi @apu52 please reopen this PR

Please make a new PR with your changes so that it will not face any merging conflicts. Please make a new branch in your forked repo then push all of your changes there & then submit your PR

**Pull request closed without merging**
