### PR TITLE
Added Loading Page With Logo

### LINKED ISSUE #214: Feature_Request : LOADING PAGE with LOGO
**Is your feature request related to a problem? Please describe.**

Yes . it's an Enhancement
**Describe the solution you'd like**

Hello all,
I want to add a loading page to our webpage  .

**Describe alternatives you've considered**

The loading page may have the name "TOURGUIDE" in blocks or maybe the logo with a loading sign . for better understanding go through the JWOC main website or look at the below SS

**Demo Video/Screenshot (Mandatory )**

image
dsfsdfsdfdfdffff

***Are you contributing under any open-source program ?***

JWOC'24

### PR DESCRIPTION
**Pull request by SohanRC**
# Title and Issue number 

Title : Added Loading Page With Logo

Issue No. : **#214**

Code Stack :  HTML , CSS , JS

Close #214 

# Video/Screenshots (mandatory)

https://github.com/apu52/Travel_Website/assets/124901633/9eb66898-284d-4a3f-aa7d-f26c75e8fefd

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

Yes , in JWOC 2024.

### CODE REVIEW

**Comment by SohanRC** [comment]
@apu52 Please review this PR.

**Comment by SohanRC** [comment]
@apu52 Also tell if some changes are required !!

**Comment by apu52** [comment]
@SohanRC please resolve the merge conflicts!!!!!!!!
Please try to resolve it ASAP!!!

**Comment by SohanRC** [comment]
@apu52 Ok wait

**Pull request closed without merging**
