### PR TITLE
Update Footer UI

### PR DESCRIPTION
**Pull request by Mubashir2611**
# feat:Adding better UI in footer section #637

Title:feat:Adding better UI in footer section #637

Issue No. :#637

Code Stack : 

Close #<issue_no>

# Description

   **Hey @apu52 I change the website footer user interface that is looked user friendly for the user. My changes included in this issue are: 
1. Cahnge the footer section background by gradient color if the user hover into the section.
2. Change the better interface of that section, Included Social Media icons in that section for better user interactivity.**  **I would like to review my PR and merge it kindly.**

# Video/Screenshots (mandatory)
image

[Screen Recording](https://github.com/apu52/Travel_Website/assets/108177382/73da30e5-504c-48a3-b8af-84c674e3cdc0)

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

# Additional context:

## Are you contributing under any Open-source programme?
Yes

### CODE REVIEW

**Review by apu52 — COMMENTED** [review]
@Mubashir2611 this PR has merge conflicts .I would like to suggest you to update your branch at first & then submit your PR , Closing this PR for now , & waiting for your new PR

**Comment by Mubashir2611** [comment]
What should I do then tell me? Why this happened all the time! And you close my pr?!

**Comment by apu52** [comment]
> @apu52 What should I do then tell me? Why this happened all the time! And you close my pr?!

Actually someone else /another contributor is also working on other issues with Footer , that's why the conflicts are constantly arising in your PR & I am closing your PR on the account that You will not face any type of conflicts farther , 

Just want to suggest u just update your branch/ make a new branch & push all of the changes there , now I think u will not face any type of conflicts .

Eager to see your PR .HAPPY CODING !!!!!!!!!!!!!

**Comment by Mubashir2611** [comment]
Please next time don't close my PR's.I work alot for those PR's

**Pull request closed without merging**
