### PR TITLE
fix: Enhanced plantrip page

### LINKED ISSUE #1493: [Feature Request]: Enhancing Plan a trip page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The tabs in the nav bar do not direct to the respective pages. I would like to make changes to make sure they are navigating to the correct pages.
Also in the trip suggestion section the cards move even if there are no further cards containing information. Changing them such that navigation stops after it reaches the last suggestion card would look good.

### Use Case

Improves user experience and easy navigation through the application.

### Benefits

_No response_

### Add ScreenShots

Screenshot 2024-10-11 103537
Screenshot 2024-10-11 103942

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

Please add the tags: hacktoberfest-accepted, hacktoberfest, gssoc-ext

### PR DESCRIPTION
**Pull request by Arveti-likhitha**
# Title and Issue number 

Title : Enhanced plan trip page

Issue No. : #1493

Code Stack :  HTML, CSS, JS

Close #1493

# Description

Made changes to make sure they are navigating to the correct pages and changing the image slider such that navigation stops after it reaches the last image card.

# Video/Screenshots (mandatory)

https://github.com/user-attachments/assets/9b08deb2-bb76-4451-8745-9b31b2320b68

# Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing
- [X] I have Starred the Repository.

# Additional context:

##Are you contributing under any Open-source programme?

- [X] I am contributing under `GSSOC'24 Extended`
- [X] I am contributing under `Hacktoberfest'24`

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@Arveti-likhitha this pr is facing some merge conflicts please try to resolve this so that I can review & merge this PR
try to update your branch(sync fork) at first then push your commits , maybe then u can avoid the conflicts

**Comment by Arveti-likhitha** [comment]
@apu52 All the conflicts are resolved.

**Comment by apu52** [comment]
@Arveti-likhitha still has conflicts

**Comment by Arveti-likhitha** [comment]
@apu52 All clear now.
image

Sorry for the trouble. There were no conflicts when commented earlier, don't know how there was a conflict again.

**Review by apu52 — APPROVED** [review]
@Arveti-likhitha okk great contribution . & really great dedication that u have crossed so much obstacles of the conflict merging problem

**Comment by Arveti-likhitha** [comment]
@apu52 Thank you for your patience with me. Wishing you all the best and hoping to contribute to your projects in the future.

**Pull request merged**
